lib.reg("lib.model",function(){});lib.Class("Model",{ns:lib.model,properties:{_data:{}},construct:function(){this._data={}},methods:{init:lib.emptyMethod,get:function(){return this._data},set:function(a){return Object.extend(this._data,a)}}});
(function(){lib.Class("SlideModel",{ns:lib.model,extend:lib.model.Model,construct:function(){this._data={first:1,focus:1,total:0,disp:0}},methods:{prev:function(){this._data.first=this._data.disp>1?Math.max(this._data.first-(this._data.disp-1),1):Math.max(this._data.first-1,1)},next:function(){if(this._data.disp>1){if(this._data.total>this._data.disp)this._data.first=Math.min(this._data.first+(this._data.disp-1),this._data.total-this._data.disp+1)}else this._data.first=Math.min(this._data.first+1,
this._data.total)},moveToFocus:function(a){this._data.focus=a;this._data.first=Math.max(1,Math.min(this._data.focus-Math.floor(this._data.disp/2),this._data.total-this._data.disp+1))},changeTotal:function(a){this._data.total=a;if(this._data.disp>1){if(this._data.total>this._data.disp)this._data.first=Math.min(this._data.first,this._data.total-this._data.disp+1)}else this._data.first=Math.min(this._data.first,this._data.total)}}})})();
(function(){lib.Class("FocusModel",{ns:lib.model,extend:lib.model.SlideModel,construct:function(a){var b=typeof a=="object"?a.url:a,c=new lib.kit.Url(window.location.href);this._url=decodeURIComponent(c.getParam("previewjs")||b);this.callsuper();this._data.last=0;this._dispCount=typeof a=="object"?a.dispCount:0},methods:{request:function(a){var b=this;window.__LT__&&(__LT__.i.focusjs=new Date);lib.kit.util.jsLoad.request(this._url,{CACHE:{varname:"ipadFocus"},onSuccess:function(c){window.__LT__&&
(__LT__.i.focusjs=new Date-__LT__.i.focusjs);b._data.nodes=b._parse(c);b._data.total=b._data.nodes.length;b._data.disp=1;a(b._data)},onError:function(){}})},_parse:function(a){for(var b=[],a=a.playlist,c=0;c<a.length;c++){if(this._dispCount&&c>this._dispCount-1)break;b.push(a[c])}return b},prev:function(){this._data.last=this._data.first;var a=this._data.first-this._data.disp,a=a>=1?a:this._data.total;this._data.first=a;this._data.dir="prev"},next:function(){this._data.last=this._data.first;var a=
this._data.first+this._data.disp,a=a<=this._data.total?a:1;this._data.first=a;this._data.dir="next"},set:function(a){this._data.last=this._data.first;return Object.extend(this._data,a)}}})})();
$reg("lib.ui.Anim",function(){var a={Linear:function(b,a,d,e){return d*b/e+a},Quad:{easeIn:function(b,a,d,e){return d*(b/=e)*b+a},easeOut:function(b,a,d,e){return-d*(b/=e)*(b-2)+a},easeInOut:function(b,a,d,e){if((b/=e/2)<1)return d/2*b*b+a;return-d/2*(--b*(b-2)-1)+a}},Cubic:{easeIn:function(b,a,d,e){return d*(b/=e)*b*b+a},easeOut:function(b,a,d,e){return d*((b=b/e-1)*b*b+1)+a},easeInOut:function(b,a,d,e){if((b/=e/2)<1)return d/2*b*b*b+a;return d/2*((b-=2)*b*b+2)+a}},Quart:{easeIn:function(b,a,d,e){return d*
(b/=e)*b*b*b+a},easeOut:function(b,a,d,e){return-d*((b=b/e-1)*b*b*b-1)+a},easeInOut:function(b,a,d,e){if((b/=e/2)<1)return d/2*b*b*b*b+a;return-d/2*((b-=2)*b*b*b-2)+a}},Quint:{easeIn:function(a,c,d,e){return d*(a/=e)*a*a*a*a+c},easeOut:function(a,c,d,e){return d*((a=a/e-1)*a*a*a*a+1)+c},easeInOut:function(a,c,d,e){if((a/=e/2)<1)return d/2*a*a*a*a*a+c;return d/2*((a-=2)*a*a*a*a+2)+c}},Sine:{easeIn:function(a,c,d,e){return-d*Math.cos(a/e*(Math.PI/2))+d+c},easeOut:function(a,c,d,e){return d*Math.sin(a/
e*(Math.PI/2))+c},easeInOut:function(a,c,d,e){return-d/2*(Math.cos(Math.PI*a/e)-1)+c}},Expo:{easeIn:function(a,c,d,e){return a==0?c:d*Math.pow(2,10*(a/e-1))+c},easeOut:function(a,c,d,e){return a==e?c+d:d*(-Math.pow(2,-10*a/e)+1)+c},easeInOut:function(a,c,d,e){if(a==0)return c;if(a==e)return c+d;if((a/=e/2)<1)return d/2*Math.pow(2,10*(a-1))+c;return d/2*(-Math.pow(2,-10*--a)+2)+c}},Circ:{easeIn:function(a,c,d,e){return-d*(Math.sqrt(1-(a/=e)*a)-1)+c},easeOut:function(a,c,d,e){return d*Math.sqrt(1-(a=
a/e-1)*a)+c},easeInOut:function(a,c,d,e){if((a/=e/2)<1)return-d/2*(Math.sqrt(1-a*a)-1)+c;return d/2*(Math.sqrt(1-(a-=2)*a)+1)+c}},Elastic:{easeIn:function(a,c,d,e,f,g){if(a==0)return c;if((a/=e)==1)return c+d;g||(g=e*0.3);!f||f<Math.abs(d)?(f=d,d=g/4):d=g/(2*Math.PI)*Math.asin(d/f);return-(f*Math.pow(2,10*(a-=1))*Math.sin((a*e-d)*2*Math.PI/g))+c},easeOut:function(a,c,d,e,f,g){if(a==0)return c;if((a/=e)==1)return c+d;g||(g=e*0.3);if(!f||f<Math.abs(d))var f=d,h=g/4;else h=g/(2*Math.PI)*Math.asin(d/
f);return f*Math.pow(2,-10*a)*Math.sin((a*e-h)*2*Math.PI/g)+d+c},easeInOut:function(a,c,d,e,f,g){if(a==0)return c;if((a/=e/2)==2)return c+d;g||(g=e*0.3*1.5);if(!f||f<Math.abs(d))var f=d,h=g/4;else h=g/(2*Math.PI)*Math.asin(d/f);if(a<1)return-0.5*f*Math.pow(2,10*(a-=1))*Math.sin((a*e-h)*2*Math.PI/g)+c;return f*Math.pow(2,-10*(a-=1))*Math.sin((a*e-h)*2*Math.PI/g)*0.5+d+c}},Back:{easeIn:function(a,c,d,e,f){f==void 0&&(f=1.70158);return d*(a/=e)*a*((f+1)*a-f)+c},easeOut:function(a,c,d,e,f){f==void 0&&
(f=1.70158);return d*((a=a/e-1)*a*((f+1)*a+f)+1)+c},easeInOut:function(a,c,d,e,f){f==void 0&&(f=1.70158);if((a/=e/2)<1)return d/2*a*a*(((f*=1.525)+1)*a-f)+c;return d/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+c}},Bounce:{easeIn:function(b,c,d,e){return d-a.Bounce.easeOut(e-b,0,d,e)+c},easeOut:function(a,c,d,e){return(a/=e)<1/2.75?d*7.5625*a*a+c:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?d*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:d*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOut:function(b,c,d,e){return b<
e/2?a.Bounce.easeIn(b*2,0,d,e)*0.5+c:a.Bounce.easeOut(b*2-e,0,d,e)*0.5+d*0.5+c}}};lib.ui._anim=Class.create({initialize:function(a){this.opt=Object.extend({duration:1E3,onStart:function(){},onDone:function(){},onCompute:function(){},interval:10,ease:"",el:null},a||{});this.ease();this.counter=0;this.el=this.opt.el?$(this.opt.el):null;this.info={}},getAnim:function(a,c,d){for(var e=[],f=0;f<a;f++)e.push(this.tweenFunc(f,c,d,a));return e},getAnimInfo:function(){this.interval=this.opt.duration/this.opt.interval;
for(var a in this.info){if(this.info[a].from==void 0)this.info[a].from=this.getDefaultFrom(this.el,a);this.info[a].unit=a=="opacity"?"":"px";this.info[a].animArray=this.getAnim(this.interval,this.info[a].from,this.info[a].to-this.info[a].from)}},getDefaultFrom:function(a,c){if(c=="scroll")return lib.box.getPageScrollTop();return parseInt(a.css(c))||0},onCompute:function(){for(var a in this.info)a=="scroll"?window.scrollTo(0,this.info[a].animArray[this.counter]):this.el.css(a,this.info[a].animArray[this.counter]+
this.info[a].unit);this.counter++},compute:function(){this.counter>=this.interval?(clearTimeout(this.iTimer),this.done(),this.counter=0):(this.onCompute(),this.iTimer=setTimeout(function(){this.compute()}.bind(this),this.opt.interval))},ease:function(b){if(!b)return this.tweenFunc=a.Linear,this;b=b.split(".");this.tweenFunc=b.length!=2?a.Linear:a[b[0]][b[1]];return this},duration:function(a){this.opt.duration=a;return this},delay:function(a){this.opt.interval=a;return this},done:function(){for(var a in this.info)a==
"scroll"?window.scrollTo(0,this.info[a].to):this.el.css(a,this.info[a].to+this.info[a].unit);if(this.opt.onDone)this.opt.onDone();this.info={}},from:function(a,c){this.info[a]||(this.info[a]={});this.info[a].from=c;return this},to:function(a,c){this.info[a]||(this.info[a]={});this.info[a].to=c;return this},scrollTo:function(a){this.info.scroll||(this.info.scroll={});this.info.scroll.to=a;return this},go:function(){this.getAnimInfo();this.inAnim=!0;this.iTimer&&clearTimeout(this.iTimer);this.compute();
return this},stop:function(){this.pause();this.counter=0},pause:function(){this.inAnim&&clearTimeout(this.iTimer);this.getAnimInfo()},resume:function(){this.compute()},onDone:function(a){this.opt.onDone=a;return this}});lib.ui.Anim=function(a){return new lib.ui._anim({el:a})}});lib.reg("lib.view",function(){});lib.Class("View",{ns:lib.view,methods:{init:lib.abstractMethod,update:lib.abstractMethod}});(function(){lib.Class("StaticView",{ns:lib.view,extend:lib.view.View,methods:{getInfo:lib.abstractMethod}})})();
(function(){lib.Class("SlideView",{ns:lib.view,extend:lib.view.StaticView,properties:{itemWidth:127,lBtnId:"j-arrowL",rBtnId:"j-arrowR",wrapperId:"j-allList",itemTag:"li",lNoneClass:"arrayLNone",rNoneClass:"arrayRNone",animEffact:"Expo.easeOut",animTime:500,animDir:"left",selectedClass:"selected",disp:7,_start:0},construct:function(a){a=a||{};Object.extend(this,a)},methods:{init:function(a){if(a)this._ctrl=a;this._initDom();this._initWrapperWidth();this._initEvent()},_initDom:function(){this._btnLeft=
lib.$("#"+this.lBtnId);this._btnRight=lib.$("#"+this.rBtnId);this._allList=lib.$("#"+this.wrapperId);this._list=this._allList.down(this.itemTag);var a=lib.$(this._list[0]);this.itemWidth=a.box().width+parseInt(a.css("marginLeft"))+parseInt(a.css("marginRight"))},_initWrapperWidth:function(){this._allList.css("width",this.itemWidth*this._list.length+20+"px")},update:function(a){lib.log("update");this._setBtnStatus(a);a.total>1&&this._playAnim(a);this._recurItem(a)},_setBtnStatus:function(a){a.first==
1?this._btnLeft.addClass(this.lNoneClass):this._btnLeft.removeClass(this.lNoneClass);a.first+a.disp-1==a.total||a.total<=a.disp?this._btnRight.addClass(this.rNoneClass):this._btnRight.removeClass(this.rNoneClass)},_playAnim:function(a){this._end=this.itemWidth*(1-a.first);this._anim=lib.ui.Anim("#"+this._allList.attr("id"));this._anim.duration(this.animTime);this._anim.ease(this.animEffact);var b=this;b._beforeAnim(a);lib.log("from "+this._start+" to "+this._end);this._anim.from(this.animDir,this._start).to(this.animDir,
this._end).go().onDone(function(){b._afterAnim(a)});this._start=this._end},_beforeAnim:function(){},_afterAnim:function(){},_recurItem:function(a){for(var b=0;b<this._list.length;b++){var c=lib.$(this._list[b]);this._checkItem(c)&&(this._setFocus(c,b,a),this._loadImg(c,b,a))}},_checkItem:function(){return!0},_setFocus:function(a,b,c){var d=lib.$(a.down("img")[0]),e=lib.$(a.down("span")[0]),f=lib.$(a.down("a")[1]),a=lib.$(a.down("a")[0]);b===c.focus-1?(d.addClass(this.selectedClass),f.addClass(this.selectedClass),
a.attr("class","imgBg1"),e.show()):(d.removeClass(this.selectedClass),f.removeClass(this.selectedClass),a.attr("class",""),e.hide())},_loadImg:function(a,b,c){var a=lib.$(a.down("img")[0]),d=a.attr("data-lazyload")||a.attr("data-lazy");if(b>=c.first-1&&b<c.first-1+c.disp&&d){a.attr("src",d);try{a.removeAttr("data-lazyload"),a.removeAttr("data-lazy")}catch(e){}}},getInfo:function(){var a=this.checkFocus(),b=1,c=this._list.length,b=Math.max(1,Math.min(a-3,c-this.disp+1));return{focus:a,total:c,disp:this.disp,
first:b}},checkFocus:function(){for(var a=1,b=0;b<this._list.length;b++)this._isFocus(lib.$(this._list[b]))&&(a=b+1);return a},_isFocus:function(){return!1},_initEvent:function(){this._bindSlideEvent();this._bindMouseEvent()},_bindSlideEvent:function(){var a=this;this._btnLeft.on("click",function(b){lib.Event.stop(b);a._btnLeft.hasClass(a.lNoneClass)||a._ctrl.prev()});this._btnRight.on("click",function(b){lib.Event.stop(b);a._btnRight.hasClass(a.rNoneClass)||a._ctrl.next()})},_bindMouseEvent:function(){}}})})();
$reg("lib.kit.iPadSlip",function(){lib.kit.iPadSlip=Class.create({initialize:function(a){this._obj=a;this._checkInterface(a);this._event=new lib.eventTarget;this._bindEvent()},on:function(a,b){this._event.on(a,b)},un:function(a,b){this._event.un(a,b)},_fire:function(a){this._event.fire(a)},_checkInterface:function(a){for(var b=["getContainer"],c=0;c<b.length;c++)if(!(b[c]in a))throw'Must implement method "'+b[c]+'".';},_bindEvent:function(){var a=this._obj.getContainer();if(a){var b=this;a.on("touchstart",
function(a){b._startX=a.touches[0].pageX;b._startY=a.touches[0].pageY;b._startTimestamp=a.timeStamp*1});a.on("touchmove",function(a){var d=a.touches[0].pageX,a=a.touches[0].pageY;b.moveStartX=b._moveStartX!=null?b._startX:b._moveStartX;b.moveStartY=b._moveStartY!=null?b._startY:b._moveStartY;d-=b.moveStartX;a-=b.moveStartY;d>0?b._fire({type:"slipDetailedRight",target:{distance:d}}):b._fire({type:"slipDetailedLeft",target:{distance:d}});a>0?b._fire({type:"slipDetailedDown",target:{distance:d}}):b._fire({type:"slipDetailedUp",
target:{distance:a}})});a.on("touchend",function(a){b._endX=a.changedTouches[0].pageX;b._endY=a.changedTouches[0].pageY;var d=b._endX-b._startX,e=b._endY-b._startY,f=a.timeStamp*1-b._startTimestamp;b.moveStartX=null;b.moveStartY=null;d>50&&b._fire({type:"slipright",target:{usedTime:f,distance:d}});d<-50&&b._fire({type:"slipleft",target:{usedTime:f,distance:d}});e>50&&b._fire({type:"slipdown",target:{usedTime:f,distance:e}});e>-50&&b._fire({type:"slipup",target:{usedTime:f,distance:e}});d==0&&e==0&&
b._fire({type:"click",event:a})})}}})});
(function(){lib.Class("FocusView",{ns:lib.view,extend:lib.view.SlideView,construct:function(a){this._param=a||{}},methods:{init:function(a){this._ctrl=a;this._itemTpl=new lib.Template('<li style="float:left;"><a href="${url}" target="${open}"><img src="${bpic}"></a></li>');this._tpl=new lib.Template('<ul style="position:relative;left:-${itemWidth}px" id="j-focusAnim">${itemCode}</ul><p id="j-focusBtn" style="position:absolute;top:0;left:0;">${btns}</p>');lib.$("#"+this._param.wrapper).show()},_initDom:function(){this._allList=
lib.$("#"+this.wrapperId);this._list=this._allList.down("li")},_initWrapperWidth:function(){this._allList.css("width",this.itemWidth*(this._list.length+2)+20+"px")},initView:function(a){if(a.nodes){this.itemWidth=this._param.width;this._start-=this.itemWidth;this.wrapperId="j-focusAnim";var b=a.nodes,c="";c+=this._itemTpl.evaluate(b[a.total-1]);for(var d=0;d<a.total;d++)c+=this._itemTpl.evaluate(b[d]);c+=this._itemTpl.evaluate(b[0]);a=this.buildBtns(a);c=this._tpl.evaluate({itemCode:c,btns:a,itemWidth:this.itemWidth});
lib.$("#"+this._param.wrapper).html(c);this._initDom();this._initWrapperWidth();this._initEvent()}},buildBtns:function(){return""},_beforeAnim:function(a){if(a.first==a.total&&a.dir=="prev")this._start=this.itemWidth*(0-a.total),this._allList.css(this.animDir,this._start+"px");else if(a.first==1&&a.dir=="next")this._start=0,this._allList.css(this.animDir,this._start+"px");this._end-=this.itemWidth*a.disp},_afterAnim:function(){this._ctrl.play()},_setBtnStatus:function(){},_setFocus:function(a,b,c){if(c)this._focusIndex=
c.first-1},_loadImg:function(){},getInfo:function(){},_isFocus:function(){},_bindSlideEvent:function(){var a=this;lib.$("#j-focusBtn").on("mouseover",function(b){if(b=parseInt(lib.$(b.srcElement||b.target).attr("_index")))a._anim&&a._anim.stop(),a._ctrl.show(b)});this._initSlip()},_bindMouseEvent:function(){var a=this;this._allList.on("mouseover",function(){a._ctrl.pause()});this._allList.on("mouseout",function(){a._ctrl.resume()})},getContainer:function(){return lib.$("#"+this._param.wrapper)},_initSlip:function(){var a=
new lib.kit.iPadSlip(this),b=this;a.on("slipleft",function(){b._anim&&b._anim.stop();b._ctrl.next()});a.on("slipright",function(){b._anim&&b._anim.stop();b._ctrl.prev()});a.on("click",function(a){if(a=lib.$(a.event.target).parent("a"))a.attr("target")!="_blank"?window.location.href=a.attr("href"):window.open(a.attr("href"))})}}})})();
(function(){lib.Class("FadeFocusView",{ns:lib.view,extend:lib.view.FocusView,properties:{_indexLableName:"img",_focusBtn:lib.$("#j-focusBtn"),_focusTitle:lib.$("#j-focusTitle"),_focusCnt:lib.$("#j-focusCnt"),_focusPlay:lib.$("#j-focusPlay")},construct:function(a){this.callsuper(a)},methods:{init:function(a){this._ctrl=a;this._itemTpl=new lib.Template('<div class="jdt_big" style="${style}"><a href="${url}" target="${open}"><img src="${bpic}"/></a></div>');this._btnTpl=new lib.Template('<li><a class="${selected}" href="${url}" target="${open}"><img src="${bpic}" _index="${index}" width="115" height="50"></a></li>');
lib.$("#"+this._param.wrapper).show();this.animTime=1E3},_initDom:function(){this._allList=lib.$("#"+this.wrapperId);this._list=this._allList.down("div")},initView:function(a){if(a.nodes){this.wrapperId="j-focusBody";for(var b=a.nodes,c="",d=0;d<a.total;d++){var e="display:none;opacity:0;";d==0&&(e="");b[d].style=e;c+=this._itemTpl.evaluate(b[d],{_index:d})}this._focusTitle.html(b[0].g_re_Title);this._focusTitle.attr("href",b[0].url);this._focusTitle.attr("target",b[0].open);this._focusCnt.html(b[0].g_re_Str);
this._focusPlay&&this._focusPlay.attr("href",b[0].url);this.buildBtns(a);lib.$("#"+this.wrapperId).html(c);this._initDom();this.doFocusChange();this._initEvent()}},_initEvent:function(){this.callsuper("_initEvent");lib._PAGE_EVENT.on("focusChanged",this.doFocusChange.bind(this))},doFocusChange:function(){var a=this._ctrl._model._data,b=lib.$(this._list[a.first-1]).down("img"),c=b.attr("src");(!c||c=="null")&&b.attr("src",a.nodes[a.first-1].bpic);a.first<a.total&&(b=lib.$(this._list[a.first]).down("img"),
c=b.attr("src"),(!c||c=="null")&&b.attr("src",a.nodes[a.first].bpic))},buildBtns:function(a){for(var b="",c=a.nodes,d=0;d<a.total;d++)c[d].selected=d==0?"selected":"",c[d].index=d+1,this.formatNodes(c[d]),b+=this._btnTpl.evaluate(c[d]);this._focusBtn.html(b);lib._PAGE_EVENT.fire({type:"buildFocusDataReady",data:{listData:a,_btnTpl:this._btnTpl}});return b},formatNodes:function(){},_playAnim:function(a){this._data=a;this._end=1;this._anim=lib.ui.Anim(this._list[a.first-1]);this._anim.duration(this.animTime);
this._anim.ease(this.animEffact);var b=this;b._beforeAnim(a);this._anim.from("opacity",this._start).to("opacity",this._end).go().onDone(function(){b._afterAnim(a)})},_beforeAnim:function(a){lib.$(this._list[a.last-1]).hide();lib.$(this._list[a.last-1]).css("opacity",0);lib.$(this._list[a.first-1]).css("opacity",0);lib.$(this._list[a.first-1]).show()},_bindSlideEvent:function(){var a=this;this._focusBtn.on("mouseover",function(b){b=b.srcElement||b.target;b.tagName.toLowerCase()==a._indexLableName&&
(a._ctrl.pause(),a._anim&&a._anim.stop(),b=parseInt(lib.$(b).attr("_index")),a._ctrl.show(b),a.doFocusChange())});this._focusBtn.on("mouseout",function(b){(b.srcElement||b.target).tagName.toLowerCase()==a._indexLableName&&a._ctrl.resume()});this._initSlip()},_setFocus:function(a,b,c){this.callsuper("_setFocus",a,b,c);var d=this._focusBtn.down("a");this._focusTitle.html(this._data.nodes[c.first-1].g_re_Title);this._focusTitle.attr("href",this._data.nodes[c.first-1].url);this._focusTitle.attr("target",
this._data.nodes[c.first-1].open);this._focusCnt.html(this._data.nodes[c.first-1].g_re_Str);this._focusPlay&&this._focusPlay.attr("href",this._data.nodes[c.first-1].url);d.removeClass("selected");d[c.first-1].className="selected";this._afterSetFocus(a,b,c)},_afterSetFocus:function(){},_setBtnStatus:function(){},_loadImg:function(){},getInfo:function(){},_isFocus:function(){},_bindMouseEvent:function(){this.callsuper("_bindMouseEvent");var a=this;this._focusPlay&&this._focusPlay.on("mouseover",function(){a._ctrl.pause()});
this._focusPlay&&this._focusPlay.on("mouseout",function(){a._ctrl.resume()})}}})})();
(function(){lib.Class("HomeFocus2View",{ns:lib.view,extend:lib.view.FadeFocusView,construct:function(a){this.callsuper(a)},methods:{init:function(a){this._ctrl=a;this._itemTpl=new lib.TemplateNew('<li style="background-image:url(${bpic});${style}"><a href="${url}" target="${open}"></a></li>');lib.$("#"+this._param.wrapper).show();this.animTime=1E3},_initDom:function(){this._allList=lib.$("#"+this.wrapperId);this._list=this._allList.down("li")},initView:function(a){lib._PAGE_EVENT.fire({type:"buildHomeFocusEnd"});
if(a.nodes){this.wrapperId="j-focusBody";for(var b=a.nodes,c="",d=0;d<a.total;d++){var e="display:none;opacity:0;";d==0&&(e="");b[d].style=e;c+=this._itemTpl.evaluate(b[d])}this.txtAnim=lib.ui.Anim(lib.$("#focusTxt"));this.txtAnim.ease("Expo.easeOut");this.txtAnim.duration(200).from("top",20).to("top",0);lib.IE7||this.txtAnim.from("opacity",0).to("opacity",1);this.txtAnim.go();lib.$("#j-focusCnt").html(b[0].g_re_Str.trancate(50));lib.$("#j-focusCnt").attr("href",b[0].url);lib.$("#j-focusPlay").attr("href",
b[0].url);this.buildBtns(a);lib.$("#"+this.wrapperId).html(c);this._initDom();this.doFocusChange();this._initEvent();lib.$("#focus-loading")&&lib.$("#focus-loading").hide()}},buildBtns:function(a){for(var a=a.nodes,b=0;a[b]&&b<10;b++){b==0||b==9?a[b].mpic&&lib.$("#j-fpic"+b).attr("src",a[b].mpic):a[b].spic&&lib.$("#j-fpic"+b).attr("src",a[b].spic);a[b].url&&lib.$("#j-flink"+b).attr("href","javascript:void(0)");var c=lib.$("#j-flink"+b);b==0?c&&c.parent().addClass("selected"):c&&c.parent().removeClass("selected")}},
getIndex:function(){var a=0;lib.$("#j-focusBtn2").down("li").each(function(b,c){if(lib.$(b).attr("class").indexOf("selected")!=-1)return a=c+1,!1});return a},_bindSlideEvent:function(){var a=this;lib.$("#j-focusBtn2").on("mouseover",function(a){a=a.srcElement||a.target;a.tagName.toLowerCase()=="a"&&(a=lib.$(a).parent("li"))&&a.addClass("liover")});lib.$("#j-focusBtn2").on("mouseout",function(a){a=a.srcElement||a.target;a.tagName.toLowerCase()=="a"&&(a=lib.$(a).parent("li"))&&a.removeClass("liover")});
lib.$("#j-focusPlay").on("click",function(b){var d=a.getIndex();lib.log("play"+d);if(window.openFocusAd)d=openFocusAd({frame:d,type:"play"}),(a.state=d)&&lib.Event.preventDefault(b)});lib.$("#j-focusCnt").on("click",function(b){var d=a.getIndex();lib.log("play"+d);if(window.openFocusAd)d=openFocusAd({frame:d,type:"play"}),(a.state=d)&&lib.Event.preventDefault(b)});var b=(new lib.kit.Url(document.location.href)).getParam("type")||"click";lib.ipod&&(b="touchstart");lib.$("#j-focusBtn2").down("a").on(b,
function(b){var d=b.srcElement||b.target;if(d.tagName.toLowerCase()=="a"){var e=parseInt(lib.$(d).attr("_index"));lib.log("small"+e);if(window.openFocusAd&&(d=openFocusAd({frame:e,type:"small"}),a.state=d)){lib.Event.preventDefault(b);return}a.txtAnim.done();a["btntimer"+e]=setTimeout(function(){a._anim&&a._anim.stop();a._ctrl.show(e);a.doFocusChange()},0)}});lib.$("#j-focusBtn2").down("a").on("mouseout",function(b){b="btntimer"+lib.$(b.srcElement||b.target).attr("_index");a[b]&&clearTimeout(a[b])});
lib.$("#j-focusclk").on("mouseover",function(){a.state||a._ctrl.pause()});lib.$("#j-focusclk").on("mouseout",function(){a.state||a._ctrl.resume()});lib.$("#j-focusclk").on("click",function(b){for(var d=b.srcElement||b.target;!~["j-focusPlay","j-focusCnt","j-focusBtn2"].indexOf(d.id)&&d.id!="j-focusclk";)d=d.parentNode;if(!~["j-focusPlay","j-focusCnt","j-focusBtn2"].indexOf(d.id)){d=a.getIndex();lib.log("big"+d);if(window.openFocusAd&&(d=openFocusAd({frame:d,type:"big"}),a.state=d)){lib.Event.preventDefault(b);
return}lib.$("#j-focusBody").down(".focus_img").each(function(a){if(!lib.$(a)[0].style.display||lib.$(a)[0].style.display=="block"){var b=lib.$(a).down("a"),a=b.attr("target"),b=b.attr("href");a&&a=="_blank"?window.open(b):location.href=b}})}});this._initSlip()},doFocusChange:function(){var a=this._ctrl._model._data,b=lib.$(this._list[a.first-1]),c=/url\("?([^"]+)"?\)/g.exec(b.css("backgroundImage"))[1];(!c||c=="null")&&b.attr("src",a.nodes[a.first-1].bpic);a.first<a.total&&(b=lib.$(this._list[a.first]),
c=/url\("?([^"]+)"?\)/g.exec(b.css("backgroundImage"))[1],(!c||c=="null")&&b.css("backgroundImage",a.nodes[a.first].bpic))},_setFocus:function(a,b,c){a=$("#j-focusBtn2").down("li");a.removeClass("selected");$(a[c.first-1]).addClass("selected");var d=this;this.timeA&&clearTimeout(this.timeA);this.timeA=setTimeout(function(){d.txtAnim.done();lib.$("#j-focusCnt").html(d._data.nodes[c.first-1].g_re_Str.trancate(50));lib.$("#j-focusCnt").attr("href",d._data.nodes[c.first-1].url);lib.$("#j-focusCnt").attr("target",
d._data.nodes[c.first-1].open);lib.$("#j-focusPlay").attr("href",d._data.nodes[c.first-1].url);lib.$("#j-focusPlay").attr("target",d._data.nodes[c.first-1].open);d.txtAnim.duration(200).from("top",20).to("top",0);lib.IE7||d.txtAnim.from("opacity",0).to("opacity",1);d.txtAnim.go()},1E3)},_beforeAnim:function(a){this.txtAnim.done();if(lib.$("#focusTxt").css("opacity")!=0){var b=lib.$("#focusTxt").css("opacity");lib.IE8||lib.IE7?(lib.log("ie8"),lib.$("#focusTxt").css("top","410px")):this.txtAnim.duration(200).from("opacity",
b).to("opacity",0).go()}this.callsuper("_beforeAnim",a)},_bindMouseEvent:function(){}}})})();
(function(){lib.Class("Adapter",{ns:lib.action,construct:function(a,b){if(a instanceof lib.model.Model)this._model=a,this._model.init(this);if(b instanceof lib.view.View)this._view=b,this._view.init(this)},methods:{syncGet:function(a){if(this._model)var b=this._model.get(a);this._view&&this._view.update(b)},asyncGet:function(a){if(!this._model)return!1;var b=this;this._model.get(a,function(a){b._view&&b._view.update(a)})},syncSet:function(a){if(this._model)var b=this._model.set(a);this._view&&this._view.update(b)},
asyncSet:function(a){if(!this._model)return!1;var b=this;this._model.set(a,function(a){b._view&&b._view.update(a)})}}})})();(function(){lib.Class("StaticAdapter",{ns:lib.action,extend:lib.action.Adapter,construct:function(a,b){this.callsuper(a,b)},methods:{init:function(a){var a=a||{},b={},c=this._view.getInfo();Object.extend(b,a);Object.extend(b,c);this._model.set(b);this.syncGet()}}})})();
(function(){lib.Class("Slide",{ns:lib.action,extend:lib.action.StaticAdapter,construct:function(a,b){this.callsuper(a,b)},methods:{prev:function(){this._model.prev();this.syncGet()},next:function(){this._model.next();this.syncGet()},moveToFocus:function(a){this._model.moveToFocus(a);this.syncGet()},changeTotal:function(a){this._model.changeTotal(a);this.syncGet()}}})})();
(function(){lib.Class("SlideFocus",{ns:lib.action,extend:lib.action.Slide,properties:{time:6E3},construct:function(a,b){this.callsuper(a,b);this.status="play"},methods:{start:function(){var a=this;this._model.request(function(b){a._view.initView(b);a.ready();a.play();lib._PAGE_EVENT.fire({type:"rerender"})})},ready:function(){},play:function(){if(this.status=="play"){var a=this;this._timer&&clearTimeout(this._timer);this._timer=setTimeout(function(){a.next();a.autoChangeFocus()},this.time)}},autoChangeFocus:function(){lib._PAGE_EVENT.fire({type:"focusChanged",
data:this._model._data})},pause:function(){this.status="stop";this._timer&&clearTimeout(this._timer)},resume:function(){this.status="play";this.play()},show:function(a){a=a||1;this._timer&&clearTimeout(this._timer);var b=this._model.get(),a=(a-1)*b.disp+1;this.syncSet({first:a,dir:""})},prev:function(){this._timer&&clearTimeout(this._timer);this.callsuper("prev")},next:function(){this._timer&&clearTimeout(this._timer);this.callsuper("next")}}})})();
(function(){lib.Class("HomeFocus",{ns:lib.action,extend:lib.action.SlideFocus,construct:function(a,b){this.callsuper(a,b);var c=this;lib._PAGE_EVENT.on("showfocusad",function(){c.pause()});lib._PAGE_EVENT.on("closefocusad",this.resume.bind(this))}})})();
(function(){lib.kit.newJob("homefocus3",function(){var a=new lib.model.FocusModel("http://www.qiyi.com/ext/common/focus/js/index2012wide.js"),b=new lib.view.HomeFocus2View({wrapper:"j-focus"}),a=new lib.action.HomeFocus(a,b);a.time=4500;a.start()});lib._PAGE_JOB.add("homefocus3")})();
(function(){lib.Class("SubscribeModel",{ns:lib.model,extend:lib.model.Model,construct:function(){this.callsuper();this._getNew="http://i."+lib.SITE_DOMAIN+"/dingyue/data/new/";this._model=lib.model({actions:{get:{method:"get",params:["subType","subKey"],format:"json",encode:!0,passport:!0,url:"isSubscribedFromJs.action"},set:{method:"get",params:["subType","subKey","logon","entry"],format:"json",encode:!0,passport:!0,url:"subscribeFromJs.action"},del:{method:"get",params:["subType","subKey"],format:"json",
encode:!0,passport:!0,url:"unsubscribeFromJs.action"}},url:"http://i."+lib.SITE_DOMAIN+"/dingyue/api/"})},methods:{init:function(){this._data={subscribed:!1,newSubscribed:!1}},getNew:function(a,b){var c=this;lib.kit.util.jsLoad.request(this._getNew,{CACHE:{varname:"lib._newSubscribe",userId:lib.cookie.get("p000email")},onSuccess:function(a){c._data.hasNew=!0;Object.extend(c._data,a);b(c._data)},onError:function(){}})},isSubscribe:function(a,b){this.init();var c=this;this._model.get(a,{success:function(){c._data.subscribed=
!0;b(c._data)},failure:function(a){c._data.subscribed=!1;Object.extend(c._data,a);b(c._data)}})},subscribe:function(a,b){this.init();var c=this;this._model.set(a,{success:function(){c._data.subscribed=!0;c._data.newSubscribed=!0;b(c._data)},failure:function(a){a.code=="A00002"?(c._data.subscribed=!0,c._data.newSubscribed=!1):c._data.subscribed=!1;Object.extend(c._data,a);b(c._data)}})},unSubscribe:function(a,b){this.init();var c=this;this._model.del(a,{success:function(){c._data.subscribed=!1;b(c._data)},
failure:function(){}})},logSubscribe:function(a){lib.kit.util.jsLoad.request("http://i."+lib.SITE_DOMAIN+"/dingyue/api/clickOnSubscribe.action",{GET:a})}}})})();(function(){lib.Class("FloaterModel",{ns:lib.model,extend:lib.model.Model,methods:{init:function(){this._data={display:!1}}}})})();
(function(){$reg("lib.ui",function(){});lib.ui.viewCenter=function(a,b){b=b||"absolute";if(a){var c=a.offsetWidth,d=a.offsetHeight,e=lib.box.getViewportWidth(),f=lib.box.getViewportHeight();if(!c||!d)throw"zero width or height.";c={left:(e-c)/2+lib.box.getPageScrollLeft(),top:(f-d)/2+lib.box.getPageScrollTop()};a.style.position=b;$(a).pos(c)}}})();
(function(){lib.Class("FloaterView",{ns:lib.view,extend:lib.view.View,construct:function(a){this.callsuper(a);this.doOnresize(a)},methods:{init:function(a){this._ctrl=a;this._elem=lib.Element.create("div");this._elem.css("position","absolute");this._elem.css("zIndex","1000");this._elem.css("overflow","hidden");this._elem.css("visibility","hidden");lib.$(document.body).append(this._elem)},update:function(a){a.display?(this.build(a),this.show(),this.showCover(),this.adjustPosition(),this.playAnim()):
(this.hide(),this.hideCover())},getFloater:function(){return this._elem},build:function(a){if(a.id){if(a=lib.$("#"+a.id))this._elem.append(a),a.show()}else a.html&&this._elem.html(a.html)},pos:function(a){this._elem.pos(a)},show:function(){this._elem.css("visibility","visible");this.hidePlayer()},hide:function(){this._elem.css("visibility","hidden");this.showPlayer()},showPlayer:function(){lib.ipad||lib._PLAYER_WMODE_SP&&lib._PLAYER_WMODE_SP.hide()},hidePlayer:function(){lib.ipad||lib._PLAYER_WMODE_SP&&
lib._PLAYER_WMODE_SP.show()},destroy:function(){this._removeEvent();this._removeDom()},adjustPosition:function(){var a=this;setTimeout(function(){lib.ui.viewCenter(a._elem[0]);a._elem.box().top<0&&a._elem.css("top","30px")},0)},showCover:function(){this._cover=lib.kit.Overlay.create({color:"#000",zIndex:112})},hideCover:function(){lib.kit.Overlay.destroy(this._cover)},playAnim:function(){},_removeDom:function(){this._elem.remove()},_removeEvent:function(){if(this.winObj)this.winObj.un("resize",this.adjustPosition),
this.winObj=null},isOpen:function(){return this._elem.css("visibility")=="visible"},doOnresize:function(a){if(a&&a.isResize)this.winObj=lib.$(window),this.winObj.on("resize",this.adjustPosition.bind(this))}}})})();
(function(){lib.Class("Floater",{ns:lib.action,extend:lib.action.Adapter,construct:function(a,b){a=a||new lib.model.FloaterModel;b=b||new lib.view.FloaterView;this.callsuper(a,b);this._valid=!0},methods:{show:function(a){a=a||{};Object.extend(a,{display:!0});this._model.set(a);this.syncGet()},hide:function(){this._model.set({display:!1});this.syncGet()},pos:function(a){this._view.pos(a)},getFloater:function(){return this._view.getFloater()},destroy:function(){this.hide();if(this._valid)this._model.destroy&&
this._model.destroy(),this._view.destroy&&this._view.destroy(),this._valid=!1},isValid:function(){return this._valid},isOpen:function(){return this._view.isOpen()}}})})();
(function(){lib.Class("RightBottomFloaterView",{ns:lib.view,extend:lib.view.FloaterView,methods:{init:function(){this.superclass.prototype.init.apply(this,arguments);this._loadedForFirstTime=!1;this._initEvent()},build:function(){this.superclass.prototype.build.apply(this,arguments);this._viewWidth=lib.box.getDocumentWidth()},adjustPosition:function(){var a=lib.box.getViewportHeight();this._elem.box();this._srcPos={right:0,top:a+lib.box.getPageScrollTop()};this._elem.pos(this._srcPos);this.showAnim()},
showAnim:function(){if(this._srcPos){var a=this._elem;a.box();this._destPos={top:this._srcPos.top-a.box().height,right:this._srcPos.right};a=lib.ui.Anim(a);a.duration(500);a.ease("Expo.easeOut");!this._loadedForFirstTime&&(a.from("top",this._srcPos.top).to("top",this._destPos.top).go(),1)||this._elem.pos(this._destPos);this._loadedForFirstTime=!0}},hideAnim:function(){if(this._srcPos&&this._destPos){var a=lib.ui.Anim(this._elem);a.duration(500);a.ease("Expo.easeOut");a.from("top",this._destPos.top).to("top",
this._srcPos.top).go().onDone(function(){})}},showCover:function(){},hideCover:function(){},_initEvent:function(){var a=this.adjustPosition.bind(this);$(window).on("resize",a);$(window).on("scroll",a)}}})})();
(function(){lib.Class("CheckSubscribeView",{ns:lib.view,extend:lib.view.View,methods:{init:function(){this._tpl=new lib.Template('<div class="gui_Qipao_wrap" id="j-suvscribePopup"><div class="gui_Qipao_box"></div><div class="gui_Qipao" style="margin-bottom:4px;"><div class="hd"><h2>\u60a8\u7684\u8ba2\u9605\u5df2\u66f4\u65b0\uff0c\u73b0\u5728\u5c31\u53bb\u770b\u770b\u5427\uff01</h2><a href="#" title="\u5173\u95ed" alt="\u5173\u95ed" onfocus="this.blur();" j-delegate="deleCloseSubscribe"></a></div><div class="bd"><dl><dt><a href="${videoUrl}"><img src="${imgUrl}" width="116" height="65" alt="${tvName}" title="${tvName}"></a></dt><dd class="dd1"><a href="${videoUrl}">${videoName}</a></dd><dd class="dd2"><a href="${videoUrl}" class="looking">\u9a6c\u4e0a\u89c2\u770b</a></dd></dl></div></div></div>')},update:function(a){if(a.hasNew){a.imgUrl=
a.imgUrl.replace(/^(.*)\.(.*)$/,"$1_116_65.$2");var a=this._tpl.evaluate(a),b=new lib.view.RightBottomFloaterView;this._floater=new lib.action.Floater(null,b);this._initEvent();this._floater.show({html:a})}},_initEvent:function(){var a=this;lib.$(document).delegate("deleCloseSubscribe",function(b){lib.Event.stop(b.event);a._floater.hide()})}}})})();
(function(){lib.Class("ConfirmModel",{ns:lib.model,extend:lib.model.FloaterModel,methods:{init:function(){this.superclass.prototype.init.apply(this,arguments);this._data={action:""}}}})})();
(function(){lib.Class("ConfirmView",{ns:lib.view,extend:lib.view.FloaterView,construct:function(a,b){this._str=a||"";b=b||{};this._htmltpl=b.tpl||'<div class="gui_Cancel_box"></div><div class="gui_Cancel"><p class="p1">${string}</p><p class="p2"><a href="#" j-delegate="confirm_apply">${apply}</a><a href="#" j-delegate="confirm_cancel">${cancel}</a></p></div>';this._applybtn=b.apply||"\u786e\u5b9a";this._cancelbtn=b.cancel||"\u53d6\u6d88"},methods:{init:function(){this.superclass.prototype.init.apply(this,
arguments);this._tpl=new lib.Template(this._htmltpl);this._initEvent()},build:function(){this._elem.html(this._tpl.evaluate({string:this._str,apply:this._applybtn,cancel:this._cancelbtn}))},_initEvent:function(){function a(b){lib.Event.stop(b.event);c._ctrl.apply();lib.$(document).undelegate("confirm_apply",a)}function b(a){lib.Event.stop(a.event);c._ctrl.cancel();lib.$(document).undelegate("confirm_cancel",b)}var c=this;lib.$(document).delegate("confirm_apply",a);lib.$(document).delegate("confirm_cancel",
b)}}})})();
(function(){lib.Class("AlertView",{ns:lib.view,extend:lib.view.FloaterView,construct:function(a,b){this._str=a||"";b=b||{};this._htmltpl=b.tpl||'<div class="gui_Cancel_box"></div><div class="gui_Cancel"><p class="p1">${string}</p><p class="p2"><a href="#" j-delegate="alert_ok">${apply}</a></p></div>';this._applybtn=b.apply||"\u786e\u5b9a"},methods:{init:function(){this.superclass.prototype.init.apply(this,arguments);this._tpl=new lib.Template(this._htmltpl);this._initEvent()},build:function(){this._elem.html(this._tpl.evaluate({string:this._str,apply:this._applybtn}))},
_initEvent:function(){function a(c){lib.Event.stop(c.event);b._ctrl.apply();lib.$(document).undelegate("alert_ok",a)}var b=this;lib.$(document).delegate("alert_ok",a)}}})})();
(function(){lib.Class("Dialog",{ns:lib.action,extend:lib.action.Floater,construct:function(a,b,c){this.callsuper(a,b);this._options=c=c||{}},statics:{confirm:function(a,b,c){var d=new lib.model.ConfirmModel,a=new lib.view.ConfirmView(a,c);(new lib.action.Dialog(d,a,{callback:b})).show()},alert:function(a,b,c){var d=new lib.model.FloaterModel,a=new lib.view.AlertView(a,c);(new lib.action.Dialog(d,a,{callback:b})).show()}},methods:{show:function(a){lib.ipad||lib._PLAYER_WMODE_SP&&lib._PLAYER_WMODE_SP.show();
a=a||{};Object.extend(a,{display:!0});this._model.set(a);this.syncGet()},hide:function(){lib.ipad||lib._PLAYER_WMODE_SP&&lib._PLAYER_WMODE_SP.hide();this._model.set({display:!1});this.syncGet()},destroy:function(){this.hide();this._model.destroy&&this._model.destroy();this._view.destroy&&this._view.destroy()},apply:function(){this.destroy();this._options.callback&&this._options.callback.call(null,{action:"apply"})},cancel:function(){this.destroy();this._options.callback&&this._options.callback.call(null,
{action:"cancel"})}}})})();
(function(){lib.Class("Subscribe",{ns:lib.action,extend:lib.action.Adapter,properties:{},construct:function(a,b,c){a=a||new lib.model.SubscribeModel;b=b||new lib.view.CheckSubscribeView;this.callsuper(a,b);c=c||{};if("getParams"in this._view)this.params=this._view.getParams()||{};this.params=this.params||{};this.params.entry=this.getEntry(c.pageName||"")},methods:{start:function(){this._checkNew()},check:function(a){var b={};Object.extend(b,this.params);Object.extend(b,a);var a=b,c=this;lib.component.login.isLogin()?
this._checkSubscribe(a,function(a){c._view.update(a)}):(this._view.resetBtns(),lib._PAGE_EVENT.fire({type:"logout_checksubscribe"}))},subscribe:function(a){var b={};Object.extend(b,this.params);Object.extend(b,a);var a=b,c=this;this._checkSubscribe(a,function(b){b.subscribed==!1?c._model.subscribe(a,function(b){c._view.update(b,a)}):(c._view.update(b),c._view.showRepeat())})},unSubscribe:function(a){var b=null,c=null;typeof a=="string"?(c=this.params,b=a):(b={},Object.extend(b,this.params),Object.extend(b,
a),a=c=b,b=a.subTvname);var d=this;lib.action.Dialog.confirm("\u60a8\u786e\u5b9a\u8981\u53d6\u6d88\u8ba2\u9605\u7684\u300a"+b+"\u300b\u7684\u76f8\u5173\u4fe1\u606f\u5417\uff1f",function(a){a.action=="apply"&&d._model.unSubscribe(c,function(a){d._view.update(a)})})},logSubscribe:function(){var a={};Object.extend(a,this.params);var b=lib.component.login.getUserInfo();a.uid=b?b.uid:"";this._model.logSubscribe(a)},_checkSubscribe:function(a,b){var c={};Object.extend(c,this.params);Object.extend(c,a);
this._model.isSubscribe(c,function(a){lib._PAGE_EVENT.fire({type:"checksubscribe",subscribed:a.subscribed});b(a)})},_checkNew:function(){var a=this;this._model.getNew(null,function(b){if(b.hasNew){var c=lib.cookie.get("Q00500");b.videoName!=c&&(lib.cookie.set("Q00500",b.videoName,8760,"/",lib.SITE_DOMAIN),a._view.update(b))}})},getEntry:function(a){switch(a){case "cartoonSetFinal":return"1-6";case "cartoonAlbum":return"1-2";case "documentFinal":return"1-7";case "documentaryAlbum":return"1-3";case "travelFinal":return"travelFinal";
case "newvariety":return"1-4";case "tvPlayFinal":return"1-5";case "tvAlbum":return"1-1";case "varietyFinal":return"1-8";case "videoclipFinal":return"1-9";case "zhuangti":return"1-10";case "search":return"1-11";case "player":return"1-12";default:return a}}}})})();(function(){var a=new lib.action.Subscribe;lib.kit.newJob("checkSubscribe",function(){lib.component.login.isLogin()&&a.start();lib.component.login.setCallback("login",function(){a.start()})});lib._PAGE_JOB.add("checkSubscribe")})();
lib.kit.newJob("floatLayerIpadFav",function(){var a=$("#j-floatLayerIpadFav");!lib.cookie.get("floatLayerIpadFav")&&lib.realIpad&&a&&(a.css("display",""),$("#j-floatLayerIpadFavClose").on("click",function(){lib.cookie.set("floatLayerIpadFav","1",8760,"/",lib.SITE_DOMAIN);a.css("display","none")}))});lib._PAGE_JOB.add("floatLayerIpadFav");
(function(){lib.Class("ToHistoryUrlView",{ns:lib.view,extend:lib.view.View,properties:{},methods:{init:function(a){this._ctrl=a;this._initDelegate()},_initDelegate:function(){$(document.body).delegate("loction2Watched",this._loction2Watched.bind(this))},_loction2Watched:function(a){this.oUrl=a.target.href;lib.Event.stop(a.event);this.oUrl&&this._ctrl.asyncGet({url:this.oUrl})},update:function(a){var b=this;a.success?lib.action.NewPlayHistory.instance.getAlbum(a.data.albumId,function(a){location.href=
a&&a.videoUrl?a.videoUrl:b.oUrl}):location.href=this.oUrl}}})})();
(function(){lib.Class("VrsAlbumIdFromUrlModel",{ns:lib.model,extend:lib.model.Model,properties:{_url:"http://cache.video.qiyi.com/aid/"},methods:{get:function(a,b){var c=this,d=new Date;lib.kit.util.jsLoad.request(this._url,{CACHE:{varname:"albumIdPurl",purl:encodeURIComponent(a.url).replace(/\+/g,"%20").replace(/%/g,"_")},onSuccess:function(a){lib.action.loadtimePingback({i_albumIdPurl_cost:new Date-d});c._data.success=!0;c._data.data=a;b(c._data)},onError:function(){c._data.success=!1;c._data.data=
null;b(c._data)},timeout:5E3})}}})})();(function(){lib.kit.newJob("toHistoryUrl",function(){var a=new lib.view.ToHistoryUrlView,b=new lib.model.VrsAlbumIdFromUrlModel;new lib.action.Adapter(b,a)});lib._PAGE_JOB.add("toHistoryUrl")})();
lib.kit.newJob("loadtime",function(a){if(window.__LT__)lib.action.loadtimePingback=function(a){lib.kit&&lib.kit.slog&&lib.kit.slog.log(a,"http://jsmsg.video.qiyi.com/l.gif")},lib.$(window).on("load",function(){__LT__.l[a]=new Date-__LT__.l.begin;var b,c;for(c in __LT__)if(__LT__[c]){var d=__LT__[c],e;for(e in d)if(typeof d[e]=="number"&&d[e]<2E4)b=b||{},b[c+"_"+e]=d[e];else if(d[e]&&d[e].start)b=b||{},b[c+"_"+e+"_start"]=d[e].start,b[c+"_"+e+"_cost"]=d[e].cost}b&&setTimeout(function(){lib.action.loadtimePingback(b)},
5E3)})});
(function(){lib.Class("HomeYuleFocusView",{ns:lib.view,extend:lib.view.FocusView,construct:function(a){this.callsuper(a)},properties:{},methods:{init:function(a){this.callsuper("init",a);this._itemTpl=new lib.Template('<li><a href="${url}" target="${open}"><img height="169" width="300" src="${bpic}"></a></li>');this._tpl=new lib.Template('<div class="pic_stroll"><ul style="position:relative;left:-${itemWidth}px;" id="j-focusAnim1">${itemCode}</ul></div><div class="pic_title"><div class="pager_control"><a id="j-yuleFocusLeft" href="javascript:" class="arrayL"></a><a id="j-yuleFocusRight" href="javascript:" class="arrayR"></a><div id="j-focusBtn" class="pager-num">${btns}</div></div><h2><a id="j-focusTitle" href="${url}">\u6768\u94b0\u83b9\u751c\u7f8e\u732e\u5531\u5bb9\u989c\u4f9d\u65e7 \u98d9\u70ed\u821e\u5f15\u5c16\u53eb</a></h2></div>')},initView:function(a){if(a.nodes){this._data=
a;this.itemWidth=this._param.width;this._start-=this.itemWidth;this.wrapperId="j-focusAnim1";var b=a.nodes,c="";c+=this._itemTpl.evaluate(b[a.total-1]);for(var d=0;d<a.total;d++)b[d].g_re_Str=b[d].g_re_Str.replace(/\n/g,"<br />"),c+=this._itemTpl.evaluate(b[d]);c+=this._itemTpl.evaluate(b[0]);a=this.buildBtns(a);c=this._tpl.evaluate({itemCode:c,btns:a,itemWidth:this.itemWidth});lib.$("#"+this._param.wrapper).html(c);lib.$("#j-focusTitle").html(this._data.nodes[0].g_re_Title);lib.$("#j-focusTitle").attr("href",
this._data.nodes[0].url);this._initDom();this._initWrapperWidth();this._initEvent()}},_bindSlideEvent:function(){var a=this;lib.$("#j-focusBtn").on("click",function(b){b=b.srcElement||b.target;b.tagName.toLowerCase()=="a"&&(a._anim&&a._anim.stop(),b=parseInt(lib.$(b).attr("_index")),a._ctrl.show(b))});this._initSlip()},_bindMouseEvent:function(){lib.$("#j-yuleFocusLeft").on("click",this._ctrl.prev.bind(this._ctrl));lib.$("#j-yuleFocusRight").on("click",this._ctrl.next.bind(this._ctrl))},buildBtns:function(a){var b=
"";if(a.nodes)for(var c=new lib.Template('<a href="javascript:" _index="${index}" class="${classname}"></a>'),d=0;d<a.total;d++)b+=c.evaluate({classname:d==0?"selected":"",index:d+1});return b},_setFocus:function(a,b,c){a=$("#j-focusBtn").down("a");a.removeClass("selected");a[c.first-1].className="selected";lib.$("#j-focusTitle").html(this._data.nodes[c.first-1].g_re_Title);lib.$("#j-focusTitle").attr("href",this._data.nodes[c.first-1].url)},_beforeAnim:function(a){if(a.first==a.total&&a.dir=="prev")this._start=
this.itemWidth*(0-(a.total+1)),this._allList.css(this.animDir,this._start+"px");else if(a.first==1&&a.dir=="next")this._start=0,this._allList.css(this.animDir,this._start+"px");this._end-=this.itemWidth*a.disp}}})})();
(function(){lib.kit.newJob("homeYuleFocus",function(){lib._PAGE_EVENT.on("buildHomeFocusEnd",function(){var a=new lib.model.FocusModel("http://www.qiyi.com/ext/common/focus/js/homeyule2012.js"),b=new lib.view.HomeYuleFocusView({wrapper:"j-homeYuleFocus",width:300,_maxNum:3}),c=new lib.action.SlideFocus(a,b);lib._PAGE_EVENT.on("rerender",function(){try{c.show(1+Math.round(Math.random()*2))}catch(a){}});c.status="stop";c.start()})});lib.$("#j-homeYuleFocus")&&lib._PAGE_JOB.add("homeYuleFocus")})();
(function(){lib.Class("HomeYuleSlideModel",{ns:lib.model,extend:lib.model.SlideModel,construct:function(){this.callsuper();this._data.last=0},methods:{prev:function(){this._data.last=this._data.first;var a=this._data.first-this._data.disp,a=a>=1?a:this._data.total;this._data.first=a;this._data.dir="prev"},next:function(){this._data.last=this._data.first;var a=this._data.first+this._data.disp,a=a<=this._data.total?a:1;this._data.first=a;this._data.dir="next"},set:function(a){this._data.last=this._data.first;
return Object.extend(this._data,a)}}})})();
(function(){lib.Class("HomeYuleSlideView",{ns:lib.view,extend:lib.view.SlideView,properties:{_btns:lib.$("#j-slideBtn")},construct:function(a){this.callsuper(a)},methods:{init:function(a){this._rebuildHtml();this.callsuper("init",a)},_rebuildHtml:function(){var a=lib.$("#"+this.wrapperId),b=a.down(this.itemTag),c=a.html(),d=lib.$(b[0]),b=lib.$(b[b.length-1]),e=lib.Element.create("div"),d=e.append(d).html();e.html("");b=e.append(b).html();a.html(b+c+d)},_setBtnStatus:function(){},_setFocus:function(a,
b,c){a=this._btns.down("a");a.removeClass("selected");a[c.first-1].className="selected"},_bindSlideEvent:function(){var a=this;this._btnLeft.on("click",function(b){lib.Event.stop(b);a._ctrl.prev()});this._btnRight.on("click",function(b){lib.Event.stop(b);a._ctrl.next()})},_bindMouseEvent:function(){var a=this;this._btns.on("click",function(b){b=b.srcElement||b.target;if(b.tagName.toLowerCase()=="a")a._anim&&a._anim.stop(),b=parseInt(lib.$(b).attr("_index")),a._cIndex=b,a._ctrl.show(b)});this._initSlip()},
_beforeAnim:function(a){if(a.first==a.total&&a.dir=="prev")this._start=this.itemWidth*(0-(a.total+1)),this._allList.css(this.animDir,this._start+"px");else if(a.first==1&&a.dir=="next")this._start=0,this._allList.css(this.animDir,this._start+"px");this._end-=this.itemWidth*a.disp},_initSlip:function(){var a=new lib.kit.iPadSlip(this),b=this;a.on("slipleft",function(){b._ctrl.next()});a.on("slipright",function(){b._ctrl.prev()});a.on("click",function(a){if(a=lib.$(a.event.target).parent("a"))a.attr("target")!=
"_blank"?window.location.href=a.attr("href"):window.open(a.attr("href"))})},getContainer:function(){return this._allList},getInfo:function(){var a=1,b=this._list.length-2,a=Math.max(1,Math.min(-2,b-this.disp+1));return{focus:1,total:b,disp:this.disp,first:a}},_loadImg:function(a,b,c){try{this.callsuper("_loadImg",a,b,c)}catch(d){}}}})})();
(function(){lib.kit.newJob("homeyuleslide",function(){if(document.getElementById("j-arrowL")&&document.getElementById("j-arrowR")&&document.getElementById("j-allList")){var a=new lib.model.HomeYuleSlideModel,b=new lib.view.HomeYuleSlideView({lBtnId:"j-arrowL",rBtnId:"j-arrowR",wrapperId:"j-allList",itemWidth:280,disp:1,itemTag:"ul"});(new lib.action.SlideFocus(a,b)).init()}});lib._PAGE_JOB.add("homeyuleslide")})();
(function(){lib.Class("TabGroups",{ns:lib.action,extend:lib.action.StaticAdapter,construct:function(a,b){this.callsuper(a,b);this._evList={}},methods:{init:function(){this.superclass.prototype.init.call(this)},select:function(a,b){this._model.set({focus:a});this.syncGet();var c=this._model.get(),d=this._evList.select,e={};e.target=b;e.data=c;if(d)for(c=0;c<d.length;c++)d[c].call(null,b,e);lib.action.lazy&&lib.action.lazy.add()},on:function(a,b){this._evList[a]||(this._evList[a]=[]);this._evList[a].push(b)},
select:function(a){this._model.set({focus:a});this.syncGet()}}})})();(function(){lib.Class("TabModel",{ns:lib.model,extend:lib.model.Model,construct:function(){this._data={focus:""}}})})();
(function(){lib.Class("TabGroupsView",{ns:lib.view,extend:lib.view.StaticView,construct:function(a,b){this.head=lib.$(a);var c=this.head.attr("j-tabbody");this.body=lib.$("#"+c);this.events=b||["click"];this.body||lib.log(c+"is not find");this.headlist=this._getHeadList();this.bodylist=this._getBodyList();this._param=this._getParam()},methods:{init:function(a){this._ctrl=a;this._bindEvent()},_getHeadList:function(){return this.head.down("*[j-tab]").elements()},_getBodyList:function(){return this.body.down("*[j-tab-cnt]").elements()},
_getParam:function(){var a={};a.selectedClass=this.head.attr("j-tabselected")||"selected";return a},_bindEvent:function(){function a(a,b,c){for(b=lib.$(b);!b.attr("j-tab");){if(b[0]==c[0])return;b=b.parent()}b=b.attr("j-tab");a._ctrl.syncSet({focus:b});lib.action.lazy&&lib.action.lazy.add()}var b=this,c=function(c,e,f){var f=f||window.event,g=f.target||f.srcElement;lib.Event.stop(f);e.length==2?setTimeout(function(){a(b,g,c)},parseInt(e[1])):a(b,g,c)};this.headlist.each(function(a){for(var a=lib.$(a),
e=null,f=0,g=b.events.length;f<g;f++)e=b.events[f].split(","),a.on(e[0],c.bind(null,a,e))})},getInfo:function(){var a={},b=this.head.down("."+this._param.selectedClass)||this.head.down("*[j-tab]");a.focus=b.attr("j-tab");return a},update:function(a){for(var b=this.headlist,c=0;c<b.length;c++){var d=lib.$(b[c]);d.attr("j-tab")==a.focus?(this._curTab=d,this.selectItem(d)):this.unselectItem(d)}b=this.bodylist;for(c=0;c<b.length;c++)d=lib.$(b[c]),d.attr("j-tab-cnt")==a.focus?(this._curCnt=d,this.show(d)):
this.hide(d);this.fireSelectEvent(a)},selectItem:function(a){a.addClass(this._param.selectedClass)},unselectItem:function(a){a.removeClass(this._param.selectedClass)},fireSelectEvent:function(a){if(a.focus){var a=this._curTab[0],b=this._curCnt[0];if(this._ctrl._evList.select)for(var c=0,d=this._ctrl._evList.select.length;c<d;c++){var e={};e.head=a;e.body=b;this._ctrl._evList.select[c].call(null,e)}}},show:function(a){a.show()},hide:function(a){a.hide()}}})})();
(function(){lib.Class("TabGroups",{ns:lib.kit,construct:function(a,b){this._tabs=[];this.tabgroup=a;this.events=b;this._evList={};this.init()},methods:{init:function(){this.getTabs()},getTabs:function(){if(lib.$("*[tab="+this.tabgroup+"]"))for(var a=lib.$("*[tab="+this.tabgroup+"]").elements(),b=0,c=a.length;b<c;b++)this.setItemTab(a[b])},setItemTab:function(a){var b=new lib.model.TabModel,a=new lib.view.TabGroupsView(a,this.events),b=new lib.action.TabGroups(b,a);this._tabs.push(b);b.init();var c=
this;b.on("select",function(a){if(c._evList.select)for(var b=0,f=c._evList.select.length;b<f;b++)c._evList.select[b].call(null,a)})},on:function(a,b){this._evList[a]||(this._evList[a]=[]);this._evList[a].push(b)},select:function(a){for(var b=0,c=this._tabs.length;b<c;b++)this._tabs[b].select(a)}}})})();(function(){lib.kit.newJob("hometabgroups",function(){(new lib.kit.TabGroups("tabgroups",["mouseover,100"])).select("t"+Math.ceil(Math.random()*2))});lib._PAGE_JOB.add("hometabgroups")})();
(function(){lib.kit.newJob("changeStyle",function(){var a=lib.$("input[changestyle]");a&&(a.on("focus",function(a){a=lib.$(a.srcElement||a.target);a.parent().addClass(a.attr("changestyle"))}),a.on("blur",function(a){a=lib.$(a.srcElement||a.target);a.parent().removeClass(a.attr("changestyle"))}))});lib._PAGE_JOB.add("changeStyle")})();
(function(){lib.Class("HomeSuggestView",{ns:lib.view,extend:lib.view.View,construct:function(){},properties:{_movieSuggest:lib.$("#movieSuggest"),_movieSousuo:lib.$("#movieSousuo"),_tvSuggest:lib.$("#tvSuggest"),_tvSousuo:lib.$("#tvSousuo"),_zongyiSuggest:lib.$("#zongyiSuggest"),_zongyiSousuo:lib.$("#zongyiSousuo"),_cartoonSuggest:lib.$("#cartoonSuggest"),_cartoonSousuo:lib.$("#cartoonSousuo"),_searchbox:lib.$("input[data-ctrl=searchbox]"),_searchbtn:lib.$("input[data-ctrl=searchbtn]")},methods:{init:function(a){this._ctrl=
a;this.bindEvent()},bindEvent:function(){if(this._searchbtn)this._searchbtn.on("click",this.sousuo.bind(this));if(this._movieSousuo)this._movieSousuo.on("click",this.sousuo.bind(this,this._movieSuggest[0]));if(this._tvSousuo)this._tvSousuo.on("click",this.sousuo.bind(this,this._tvSuggest[0]));if(this._zongyiSousuo)this._zongyiSousuo.on("click",this.sousuo.bind(this,this._zongyiSuggest[0]));if(this._cartoonSousuo)this._cartoonSousuo.on("click",this.sousuo.bind(this,this._cartoonSuggest[0]));if(this._searchbox)this._searchbox.on("focus",
this.processFocus.bind(this));if(this._movieSuggest)this._movieSuggest.on("focus",this.processFocus.bind(this,this._movieSuggest));if(this._tvSuggest)this._tvSuggest.on("focus",this.processFocus.bind(this,this._tvSuggest));if(this._zongyiSuggest)this._zongyiSuggest.on("focus",this.processFocus.bind(this,this._zongyiSuggest));if(this._cartoonSuggest)this._cartoonSuggest.on("focus",this.processFocus.bind(this,this._cartoonSuggest));if(this._searchbox)this._searchbox.on("blur",this.processBlur.bind(this));
if(this._movieSuggest)this._movieSuggest.on("blur",this.processBlur.bind(this,this._movieSuggest));if(this._tvSuggest)this._tvSuggest.on("blur",this.processBlur.bind(this,this._tvSuggest));if(this._zongyiSuggest)this._zongyiSuggest.on("blur",this.processBlur.bind(this,this._zongyiSuggest));if(this._cartoonSuggest)this._cartoonSuggest.on("blur",this.processBlur.bind(this,this._cartoonSuggest));if(this._searchbox)this._searchbox.on("keyup",this.onKeyUp.bind(this));if(this._movieSuggest)this._movieSuggest.on("keyup",
this.onKeyUp.bind(this));if(this._tvSuggest)this._tvSuggest.on("keyup",this.onKeyUp.bind(this));if(this._zongyiSuggest)this._zongyiSuggest.on("keyup",this.onKeyUp.bind(this));if(this._cartoonSuggest)this._cartoonSuggest.on("keyup",this.onKeyUp.bind(this));this._searchbox&&(this._searchbox.on("mouseover",function(a){lib.$(a.target||a.srcElement).parent().parent().addClass("sou-panel_onhover")}),this._searchbox.on("mouseout",function(a){lib.$(a.target||a.srcElement).parent().parent().removeClass("sou-panel_onhover")}))},
update:function(a){lib.log(a)},sousuo:function(a){!a.parentNode&&(a=lib.$(a.srcElement||a.target).parent().parent().down("input[data-ctrl=searchbox]")[0]);a.value=a.value==""?a.getAttribute("j-defaultvalue"):a.value;var b=new lib.kit.Url(location.href),c=window;b.getParam("pr")=="baidu"&&(c=top);c.location=["http://so.qiyi.com/so/q",encodeURIComponent(a.value),"f_2"].join("_")},processFocus:function(a){this._searchbox&&(a=lib.$(a.srcElement||a.target),a.parent().parent().addClass("sou-panel_click"));
a.val()==a.attr("j-defaultvalue")&&a.val("")},processBlur:function(a){this._searchbox&&(a=lib.$(a.srcElement||a.target),a.parent().parent().removeClass("sou-panel_click"));a.val()==""&&a.val(a.attr("j-defaultvalue"))},onKeyUp:function(a){var b=a.srcElement||a.target;a.keyCode==13&&this.sousuo(b)}}})})();(function(){lib.kit.newJob("homesuggest",function(){var a=new lib.model.Model,b=new lib.view.HomeSuggestView;new lib.action.Adapter(a,b)});lib._PAGE_JOB.add("homesuggest")})();
(function(){lib.kit.newJob("hometopdiv",function(){if(lib.$("#j-hometopdiv")){lib.IE6&&lib.$(document.getElementsByTagName("html")[0]).css("overflowY","scroll");(new lib.action.Floater).show({id:"j-hometopdiv"});var a=window.external,b=window.sidebar;if(/se \d\.x/.test(navigator.userAgent.toLowerCase())||lib.Maxthon||!lib.CHROME&&!lib.IE7&&(a||b))lib.$("#baidupopfav").show(),lib.$("#baidupopfav").on("click",function(){var c="http://www."+lib.SITE_DOMAIN;b?b.addPanel("\u7231\u5947\u827a-\u4e2d\u56fd\u7b2c\u4e00\u5f71\u89c6\u95e8\u6237 \u9ad8\u6e05\u5f71\u89c6\u5267\u3001\u7f51\u7edc\u89c6\u9891\u5728\u7ebf\u89c2\u770b",
c,""):a&&("addFavorite"in a?a.addFavorite(c,"\u7231\u5947\u827a-\u4e2d\u56fd\u7b2c\u4e00\u5f71\u89c6\u95e8\u6237 \u9ad8\u6e05\u5f71\u89c6\u5267\u3001\u7f51\u7edc\u89c6\u9891\u5728\u7ebf\u89c2\u770b"):"AddFavorite"in a&&a.AddFavorite(c,"\u7231\u5947\u827a-\u4e2d\u56fd\u7b2c\u4e00\u5f71\u89c6\u95e8\u6237 \u9ad8\u6e05\u5f71\u89c6\u5267\u3001\u7f51\u7edc\u89c6\u9891\u5728\u7ebf\u89c2\u770b"))});var c=5,d=setInterval(function(){lib.$("#j-hometopdivtimer").html(c);c--;if(c==0)clearInterval(d),top.location.href=
"http://www."+lib.SITE_DOMAIN},1E3)}});(new lib.kit.Url(location.href)).getParam("pr")=="baidu"&&lib._PAGE_JOB.add("hometopdiv")})();var Tween={};
(function(){function a(a){a=a.constructor.toString().toLowerCase();return a.slice(a.indexOf("function")+9,a.indexOf("()"))}function b(a,b){var c,d,e=[];d=b.length;var f=0;for(c=0;c<d;c++)"rotate"==b[c]?(b[c]="-webkit-transform",a.style[b[c]]?(f=a.style[b[c]].replace(/[^0-9-]/ig,""),f=f==""?0:f):f=0):"-webkit-transform"==b[c]?(f=a.style[b[c]].replace(/[^0-9-]/ig,""),f=f==""?0:f):f=a.style[b[c]]?a.style[b[c]]:0,e[e.length]=parseFloat(f);return e}function c(b,c){var e=[],f=[],g,i,h;if(a(b)!="array")h=
d(b),h[1]=c=="opacity"?"":h[1],e=[h[0]],f=[h[1]];else{i=b.length;for(g=0;g<i;g++)h=d(b[g]),h[1]=c[g]=="opacity"?"":h[1],e[e.length]=h[0],f[f.length]=h[1]}return[e,f]}function d(a){a=/(-?\d.?\d*)([a-z%]*)/i.exec(a);return[a[1],a[2]?a[2]:"px"]}function e(a){var b=j(a),c;return k[b]!=!0?(c=new f,l[b]={node:a,func:c},k[b]=!0,c):l[b].func}function f(){this._timer=null}function g(a){var b=e(a);b.start.apply(b,arguments)}var h={simple:function(a,b,c,d){return c*a/d+b},backEaseIn:function(a,b,c,d){return c*
(a/=d)*a*(2.70158*a-1.70158)+b},backEaseOut:function(a,b,c,d){return c*((a=a/d-1)*a*(2.70158*a+1.70158)+1)+b},backEaseInOut:function(a,b,c,d){var e=1.70158;if((a/=d/2)<1)return c/2*a*a*(((e*=1.525)+1)*a-e)+b;return c/2*((a-=2)*a*(((e*=1.525)+1)*a+e)+2)+b},bounceEaseOut:function(a,b,c,d){return(a/=d)<1/2.75?c*7.5625*a*a+b:a<2/2.75?c*(7.5625*(a-=1.5/2.75)*a+0.75)+b:a<2.5/2.75?c*(7.5625*(a-=2.25/2.75)*a+0.9375)+b:c*(7.5625*(a-=2.625/2.75)*a+0.984375)+b},bounceEaseIn:function(a,b,c,d){return c-h.bounceEaseOut(d-
a,0,c,d)+b},bounceEaseInOut:function(a,b,c,d){return a<d/2?h.bounceEaseIn(a*2,0,c,d)*0.5+b:h.bounceEaseOut(a*2-d,0,c,d)*0.5+c*0.5+b},strongEaseInOut:function(a,b,c,d){return c*(a/=d)*a*a*a*a+b},regularEaseIn:function(a,b,c,d){return c*(a/=d)*a+b},regularEaseOut:function(a,b,c,d){return-c*(a/=d)*(a-2)+b},regularEaseInOut:function(a,b,c,d){if((a/=d/2)<1)return c/2*a*a+b;return-c/2*(--a*(a-2)-1)+b},strongEaseIn:function(a,b,c,d){return c*(a/=d)*a*a*a*a+b},strongEaseOut:function(a,b,c,d){return c*((a=
a/d-1)*a*a*a*a+1)+b},strongEaseInOut:function(a,b,c,d){if((a/=d/2)<1)return c/2*a*a*a*a*a+b;return c/2*((a-=2)*a*a*a*a+2)+b},elasticEaseIn:function(a,b,c,d,e,f){if(a==0)return b;if((a/=d)==1)return b+c;f||(f=d*0.3);!e||e<Math.abs(c)?(e=c,c=f/4):c=f/(2*Math.PI)*Math.asin(c/e);return-(e*Math.pow(2,10*(a-=1))*Math.sin((a*d-c)*2*Math.PI/f))+b},elasticEaseOut:function(a,b,c,d,e,f){if(a==0)return b;if((a/=d)==1)return b+c;f||(f=d*0.3);if(!e||e<Math.abs(c))var e=c,g=f/4;else g=f/(2*Math.PI)*Math.asin(c/
e);return e*Math.pow(2,-10*a)*Math.sin((a*d-g)*2*Math.PI/f)+c+b},elasticEaseInOut:function(a,b,c,d,e,f){if(a==0)return b;if((a/=d/2)==2)return b+c;f||(f=d*0.3*1.5);if(!e||e<Math.abs(c))var e=c,g=f/4;else g=f/(2*Math.PI)*Math.asin(c/e);if(a<1)return-0.5*e*Math.pow(2,10*(a-=1))*Math.sin((a*d-g)*2*Math.PI/f)+b;return e*Math.pow(2,-10*(a-=1))*Math.sin((a*d-g)*2*Math.PI/f)*0.5+c+b},expoEaseIn:function(a,b,c,d){return a==0?b:c*Math.pow(2,10*(a/d-1))+b}},j=function(a){return a.uniqueID};lib.IE||(j=function(a){var b;
if(a.getAttribute("uniqueID")==null)return b="moz__id"+parseInt(Math.random()*100)+"_"+(new Date).getTime(),a.setAttribute("uniqueID",b),b;return a.getAttribute("uniqueID")});var k={},l={};f.prototype.start=function(d,e,f,g,j,i){this.reset();i=i||{};if(i.end)this._func.end=i.end;if(i.tween)this._func.tween=i.tween;e=a(e)!="array"?[e]:e;i=b(d,e);f=c(f,e);this._node=d;this._property=e;this._endingvalue=f[0];this._suffixvalue=f[1];this._startvalue=i;this._end=!1;this._fps=0;if(g!=null)this._seconds=
g;if(h[j]!=null)this._animation=h[j];this._starttime=(new Date).getTime();var k=this;this._timer=setInterval(function(){k.play()},10)};f.prototype.play=function(){var a=((new Date).getTime()-this._starttime)/1E3,b,c,d=this._property.length;if(a>this._seconds)a=this._seconds;for(b=0;b<d;b++){c=this._animation(a,this._startvalue[b],this._endingvalue[b]-this._startvalue[b],this._seconds);var e={};e[this._property[b]]=isNaN(c)?"1":c+this._suffixvalue[b];"-webkit-transform"==this._property[b]&&(e[this._property[b]]=
"rotate("+c+"deg)");$(this._node).css(this._property[b],e[this._property[b]])}this._fps++;this._func.tween();a==this._seconds&&this.stop()};f.prototype.stop=function(){clearInterval(this._timer);this._end=!0;this._func.end()};f.prototype.reset=function(){clearInterval(this._timer);this._end=!1;this._node=null;this._property=[];this._startvalue=[];this._endingvalue=[];this._suffixvalue=[];this._fps=0;this._seconds=0.5;this._animation=h.simple;this._func={end:function(){},tween:function(){}}};g.stop=
function(a){e(a).stop()};g.isTween=function(a){return!e(a)._end};Tween=g})();
(function(){$reg("lib.action.Focus",function(){lib.action.Focus=Class.create({initialize:function(a,b){this._nodes=[];this._parent=$(b.parent);this._curr=0;this._queueMax=3;this._duringAnim=!1;this._queue=[];var c=this;lib.kit.util.jsLoad.request(a,{CACHE:{varname:"ipadFocus"},onSuccess:function(a){c._parse(a);c._face=new b.face(c._nodes,{width:b.width,height:b.height,opacity:b.opacity,logo:b.logo});c._animate=new b.animate({width:b.width,height:b.height});c._initSlip();c.start()}})},_parse:function(a){for(var a=
a.playlist,b=0;b<a.length;b++)this._nodes.push(a[b]);this._max=this._nodes.length},start:function(){this._face.show(this._parent);var a=this;this._animate.on("finish",function(){a._duringAnim=!1;if(a._queue.length>0){var b=a._queue.splice(0,1);b=="left"&&a._playNext(0);b=="right"&&a._playPrev(0)}else a._playNext(3E3)});this._playNext(3E3)},_delay:function(a,b){this._animTimer&&clearTimeout(this._animTimer);this._animTimer=setTimeout(a,b)},_playNext:function(a){var b=this;this._delay(function(){var a=
b._face.getItem(b._curr++);if(b._curr>b._max-1)b._curr=0;var d=b._face.getItem(b._curr);b._duringAnim=!0;b._animate.play(a,d,{dir:"left"})},a)},_playPrev:function(a){var b=this;this._delay(function(){var a=b._face.getItem(b._curr--);if(b._curr<0)b._curr=b._max-1;var d=b._face.getItem(b._curr);b._duringAnim=!0;b._animate.play(a,d,{dir:"right"})},a)},_initSlip:function(){var a=new lib.kit.iPadSlip(this),b=this;a.on("slipleft",function(){b._duringAnim===!0?b._queue.length<b._queueMax&&b._queue.push("left"):
b._playNext(0)});a.on("slipright",function(){b._duringAnim===!0?b._queue.length<b._queueMax&&b._queue.push("right"):b._playPrev(0)});a.on("click",function(a){if(a=lib.$(a.event.target).parent("a"))a.attr("target")!="_blank"?window.location.href=a.attr("href"):window.open(a.attr("href"))})},getContainer:function(){return this._parent}})});$reg("lib.action.FocusFace",function(){lib.action.FocusFace=Class.create({initialize:function(a,b){this.html="";for(var c=[],d=b.width,e=b.height,f=b.opacity,g=0;g<
a.length;g++){var h=a[g];c.push('<div style="{2}"><a href="{0}" target="{6}"><img src="{1}"/><p class="cnt" style="{5}"><strong>{3}</strong><br/><br/><span>{4}</span><a href="{0}" class="btn" target="{6}"></a></p>'.format(h.url,h.bpic,g==0?"left:0px;opacity:1;":"left:"+d+"px;opacity:"+(typeof f=="undefined"?1:f)+";",h.g_re_Title,h.g_re_Str,g==0?"height:"+e+"px;":"height:0px;",h.open));c.push("</div>")}b.logo===!0&&c.push('<span class="logo"></span>');this.html=c.join("")},show:function(a){this._parent=
a;a.html(this.html)},getItem:function(a){if(!this._items){var b=lib.$("div",this._parent[0]),c=lib.$("p",this._parent[0]);this._items=[];for(var d=0;d<b.length;d++)this._items.push({div:lib.$(b[d]),p:lib.$(c[d])})}return this._items[a]}})});$reg("lib.action.FocusAnimate",function(){lib.action.FocusAnimate=Class.create({initialize:function(a){this._params=a;this._event=new lib.eventTarget},on:function(a,b){this._event.on(a,b)},un:function(a,b){this._event.un(a,b)},_fire:function(a){this._event.fire(a)},
play:function(a,b,c){var d=this,e=this._params.width,f=this._params.height,c=c||{};(c.dir||"left")==="left"?(b.div.css("left",e+"px"),c=0-e):(b.div.css("left",0-e+"px"),c=e);b.p.css("height","0px");new Tween(a.div[0],["left","opacity"],[c,0],0.5,"simple",{tween:function(){new Tween(b.div[0],["left","opacity"],[0,0.99],0.5,"simple",{end:function(){new Tween(b.p[0],"height",f,0.5,"simple",{end:function(){d._fire({type:"finish"})}})}})}})}})})})();
(function(){$reg("lib.action.HomeFocusAnimate",function(){lib.action.HomeFocusAnimate=Class.create({initialize:function(a){this._params=a;this._event=new lib.eventTarget},on:function(a,b){this._event.on(a,b)},un:function(a,b){this._event.un(a,b)},_fire:function(a){this._event.fire(a)},play:function(a,b,c){var d=this,e=this._params.width,f=this._params.height,c=c||{};(c.dir||"left")==="left"?(b.div.css("left",e+"px"),c=0-e):(b.div.css("left",0-e+"px"),c=e);b.p.css("height","0px");new Tween(a.div[0],
"left",c,0.5,"simple",{tween:function(){new Tween(b.div[0],"left",0,0.5,"simple",{end:function(){new Tween(b.p[0],"height",f,0.5,"simple",{end:function(){d._fire({type:"finish"})}})}})}})}})})})();
(function(){var a=["iPadAdResource","iPadAdResource_1"],b={};a.each(function(a){b[a]=lib.$("[data-widget="+a.toLowerCase()+"]")});lib.kit.newJob("iPadAdResource",function(){a.each(function(a){var d="";if(lib.temp[a]&&lib.temp[a].resources){var e=lib.temp[a].resources.length;if(e){b[a].css("display")=="none"&&b[a].css("display","");for(var f=0;f<e;f++){var g=lib.temp[a].resources[f];g.display=f==0?"block":"none";var h=new lib.Template(g.tpl);d+=h.evaluate(g)}b[a].html(d);if(e>1){var j=1;setInterval(function(){var d=
b[a].down("[data-elem=ipadaditem]");d.hide();j%=e;lib.$(d[j]).show();j++},lib.temp[a].interval)}}}})});a.filter(function(a){return lib.temp[a]&&b[a]}).length&&lib._PAGE_JOB.add("iPadAdResource")})();
lib.kit.newJob("addUnderline",function(){var a=lib.$("*[data-widget=addunderline]");a&&(a.on("mouseenter",function(a){for(a=lib.$(a.target||a.srcElement);a&&a.attr("data-widget")!="addunderline";)a=a.parent();a&&a.down("a").each(function(a){var b=a.css("textDecoration")||"";b!="underline"&&(a.attr("data-textdecoration",b),a.css("textDecoration","underline"))})}),a.on("mouseleave",function(a){for(a=lib.$(a.target||a.srcElement);a&&a.attr("data-widget")!="addunderline";)a=a.parent();a&&a.down("a").each(function(a){var b=
a.attr("data-textdecoration");b&&a.css("textDecoration",b)})}))});lib._PAGE_JOB.add("addUnderline");(function(){lib.Class("FloaterLicenseView",{ns:lib.view,extend:lib.view.FloaterView,methods:{adjustPosition:function(){var a=this;setTimeout(function(){a._elem.box();lib.ui.viewCenter(a._elem[0])},0)}}})})();
(function(){lib.kit.newJob("licenseFloater",function(){var a=lib.$("#j-net-license-btn"),b=lib.$("#j-broadcast-license-btn");if(a||b){var c=new lib.model.FloaterModel,d=new lib.view.FloaterLicenseView,e=new lib.action.Floater(c,d),f=['<div class="xkPopbox">','<a data-btn="j-close-btn" class="xclose" href="#"></a>','<img data-type="net" alt="\u7f51\u7edc\u6587\u5316\u7ecf\u8425\u8bb8\u53ef\u8bc1" src="http://www.qiyipic.com/common/fix/index_images/xkz_wl.png" style="display:none;width:450px;height:330px;">',
'<img data-type="broadcast" alt="\u5e7f\u64ad\u7535\u89c6\u8282\u76ee\u5236\u4f5c\u7ecf\u8425\u8bb8\u53ef\u8bc1" src="http://www.qiyipic.com/common/fix/index_images/xkz_gb.png" style="display:none;width:440px;height:330px;">',"</div>"],g=e.getFloater(),c=function(a){lib.Event.stop(a)};g.on("contextmenu",c);g.on("selectstart",c);g.on("select",c);g.on("copy",c);g.on("beforecopy",c);c=function(a,b){lib.Event.stop(b);e.show({html:f.join("")});var c=g.down("a[data-btn=j-close-btn");if(c)c.on("click",function(a){lib.Event.stop(a);
e.hide()});g.down("img[data-type="+a+"]").show()};if(a)a.on("click",c.bind(null,"net"));if(b)b.on("click",c.bind(null,"broadcast"))}});lib._PAGE_JOB.add("licenseFloater")})();lib.kit.newJob("crestAd",function(){var a=lib.$("#adBackground"),b=lib.$("#adCloseBtn"),c=lib.cookie.get("TQC001");a&&b&&!lib.ipad&&(c!="true"&&a.addClass("wider"),b.on("click",function(b){lib.Event.stop(b);a.removeClass("wider");lib.cookie.set("TQC001","true",12,"/",lib.SITE_DOMAIN)}))});lib._PAGE_JOB.add("crestAd");
(function(){lib._PAGE_JOB.add("loadtime","home");lib._PAGE_JOB.start()})();
