/*
 SeaJS - A Module Loader for the Web
 v1.2.1 | seajs.org | MIT Licensed
*/
window.seajs||(this.seajs={_seajs:this.seajs},seajs.version="1.2.1",seajs._util={},seajs._config={debug:"%DEBUG%",preload:[]},function(a){var b=Object.prototype.toString,f=Array.prototype;a.isString=function(a){return"[object String]"===b.call(a)};a.isFunction=function(a){return"[object Function]"===b.call(a)};a.isRegExp=function(a){return"[object RegExp]"===b.call(a)};a.isObject=function(a){return a===Object(a)};a.isArray=Array.isArray||function(a){return"[object Array]"===b.call(a)};a.indexOf=f.indexOf?
function(a,b){return a.indexOf(b)}:function(a,b){for(var e=0;e<a.length;e++)if(a[e]===b)return e;return-1};var d=a.forEach=f.forEach?function(a,b){a.forEach(b)}:function(a,b){for(var e=0;e<a.length;e++)b(a[e],e,a)};a.map=f.map?function(a,b){return a.map(b)}:function(a,b){var e=[];d(a,function(a,d,c){e.push(b(a,d,c))});return e};a.filter=f.filter?function(a,b){return a.filter(b)}:function(a,b){var e=[];d(a,function(a,d,c){b(a,d,c)&&e.push(a)});return e};var c=a.keys=Object.keys||function(a){var b=
[],e;for(e in a)a.hasOwnProperty(e)&&b.push(e);return b};a.unique=function(a){var b={};d(a,function(a){b[a]=1});return c(b)};a.now=Date.now||function(){return(new Date).getTime()}}(seajs._util),function(a,b){var f=Array.prototype;a.log=function(){if("undefined"!==typeof console){var a=f.slice.call(arguments),c="log";console[a[a.length-1]]&&(c=a.pop());if("log"!==c||b.debug)a="dir"===c?a[0]:f.join.call(a," "),console[c](a)}}}(seajs._util,seajs._config),function(a,b,f){function d(a){a=a.match(j);return(a?
a[0]:".")+"/"}function c(a){h.lastIndex=0;h.test(a)&&(a=a.replace(h,"$1/"));if(-1===a.indexOf("."))return a;for(var b=a.split("/"),e=[],d,c=0;c<b.length;c++)if(d=b[c],".."===d){if(0===e.length)throw Error("The path is invalid: "+a);e.pop()}else"."!==d&&e.push(d);return e.join("/")}function n(a){var a=c(a),b=a.charAt(a.length-1);if("/"===b)return a;"#"===b?a=a.slice(0,-1):-1===a.indexOf("?")&&!g.test(a)&&(a+=".js");0<a.indexOf(":80/")&&(a=a.replace(":80/","/"));return a}function l(a){if("#"===a.charAt(0))return a.substring(1);
var e=b.alias;if(e&&o(a)){var d=a.split("/"),c=d[0];e.hasOwnProperty(c)&&(d[0]=e[c],a=d.join("/"))}return a}function e(a){return 0<a.indexOf("://")||0===a.indexOf("//")}function k(a){return"/"===a.charAt(0)&&"/"!==a.charAt(1)}function o(a){var b=a.charAt(0);return-1===a.indexOf("://")&&"."!==b&&"/"!==b}var j=/.*(?=\/.*$)/,h=/([^:\/])\/\/+/g,g=/\.(?:css|js)$/,m=/^(.*?\w)(?:\/|$)/,i={},f=f.location,p=f.protocol+"//"+f.host+function(a){"/"!==a.charAt(0)&&(a="/"+a);return a}(f.pathname);0<p.indexOf("\\")&&
(p=p.replace(/\\/g,"/"));a.dirname=d;a.realpath=c;a.normalize=n;a.parseAlias=l;a.parseMap=function(e){var d=b.map||[];if(!d.length)return e;for(var c=e,h=0;h<d.length;h++){var f=d[h];if(a.isArray(f)&&2===f.length){var k=f[0];if(a.isString(k)&&-1<c.indexOf(k)||a.isRegExp(k)&&k.test(c))c=c.replace(k,f[1])}else a.isFunction(f)&&(c=f(c))}c!==e&&(i[c]=e);return c};a.unParseMap=function(a){return i[a]||a};a.id2Uri=function(a,c){if(!a)return"";a=l(a);c||(c=p);var h;e(a)?h=a:0===a.indexOf("./")||0===a.indexOf("../")?
(0===a.indexOf("./")&&(a=a.substring(2)),h=d(c)+a):h=k(a)?c.match(m)[1]+a:b.base+"/"+a;return n(h)};a.isAbsolute=e;a.isRoot=k;a.isTopLevel=o;a.pageUri=p}(seajs._util,seajs._config,this),function(a,b){function f(a,c){a.onload=a.onerror=a.onreadystatechange=function(){j.test(a.readyState)&&(a.onload=a.onerror=a.onreadystatechange=null,a.parentNode&&!b.debug&&e.removeChild(a),a=void 0,c())}}function d(b,e){i||p?(a.log("Start poll to fetch css"),setTimeout(function(){c(b,e)},1)):b.onload=b.onerror=function(){b.onload=
b.onerror=null;b=void 0;e()}}function c(a,b){var e;if(i)a.sheet&&(e=!0);else if(a.sheet)try{a.sheet.cssRules&&(e=!0)}catch(d){"NS_ERROR_DOM_SECURITY_ERR"===d.name&&(e=!0)}setTimeout(function(){e?b():c(a,b)},1)}function n(){}var l=document,e=l.head||l.getElementsByTagName("head")[0]||l.documentElement,k=e.getElementsByTagName("base")[0],o=/\.css(?:\?|$)/i,j=/loaded|complete|undefined/,h,g;a.fetch=function(b,c,i){var j=o.test(b),g=document.createElement(j?"link":"script");i&&(i=a.isFunction(i)?i(b):
i)&&(g.charset=i);c=c||n;"SCRIPT"===g.nodeName?f(g,c):d(g,c);j?(g.rel="stylesheet",g.href=b):(g.async="async",g.src=b);h=g;k?e.insertBefore(g,k):e.appendChild(g);h=null};a.getCurrentScript=function(){if(h)return h;if(g&&"interactive"===g.readyState)return g;for(var a=e.getElementsByTagName("script"),b=0;b<a.length;b++){var c=a[b];if("interactive"===c.readyState)return g=c}};a.getScriptAbsoluteSrc=function(a){return a.hasAttribute?a.src:a.getAttribute("src",4)};a.importStyle=function(a,b){if(!b||!l.getElementById(b)){var c=
l.createElement("style");b&&(c.id=b);e.appendChild(c);c.styleSheet?c.styleSheet.cssText=a:c.appendChild(l.createTextNode(a))}};var m=navigator.userAgent,i=536>Number(m.replace(/.*AppleWebKit\/(\d+)\..*/,"$1")),p=0<m.indexOf("Firefox")&&!("onload"in document.createElement("link"))}(seajs._util,seajs._config,this),function(a){var b=/(?:^|[^.$])\brequire\s*\(\s*(["'])([^"'\s\)]+)\1\s*\)/g;a.parseDependencies=function(f){var d=[],c,f=f.replace(/^\s*\/\*[\s\S]*?\*\/\s*$/mg,"").replace(/^\s*\/\/.*$/mg,
"");for(b.lastIndex=0;c=b.exec(f);)c[2]&&d.push(c[2]);return a.unique(d)}}(seajs._util),function(a,b,f){function d(a,b){this.uri=a;this.status=b||0}function c(a,e){return b.isString(a)?d._resolve(a,e):b.map(a,function(a){return c(a,e)})}function n(a,e){var c=b.parseMap(a);q[c]?(h[a]=h[c],e()):p[c]?t[c].push(e):(p[c]=!0,t[c]=[e],d._fetch(c,function(){q[c]=!0;var e=h[a];e.status===i.FETCHING&&(e.status=i.FETCHED);u&&(l(a,u),u=null);r&&e.status===i.FETCHED&&(h[a]=r,r.realUri=a);r=null;p[c]&&delete p[c];
t[c]&&(b.forEach(t[c],function(a){a()}),delete t[c])},f.charset))}function l(a,e){var s=h[a]||(h[a]=new d(a));s.status<i.SAVED&&(s.id=e.id||a,s.dependencies=c(b.filter(e.dependencies||[],function(a){return!!a}),a),s.factory=e.factory,s.status=i.SAVED);return s}function e(a,b){var e=a(b.require,b.exports,b);void 0!==e&&(b.exports=e)}function k(a){var c=a.realUri||a.uri,d=g[c];d&&(b.forEach(d,function(b){e(b,a)}),delete g[c])}function o(a){var e=a.uri;return b.filter(a.dependencies,function(a){v=[e];
if(a=j(h[a],e))v.push(e),b.log("Found circular dependencies:",v.join(" --\> "),void 0);return!a})}function j(a,e){if(!a||a.status!==i.SAVED)return!1;v.push(a.uri);var c=a.dependencies;if(c.length){if(-1<b.indexOf(c,e))return!0;for(var d=0;d<c.length;d++)if(j(h[c[d]],e))return!0}return!1}var h={},g={},m=[],i={FETCHING:1,FETCHED:2,SAVED:3,READY:4,COMPILING:5,COMPILED:6};d.prototype._use=function(a,e){b.isString(a)&&(a=[a]);var d=c(a,this.uri);this._load(d,function(){var a=b.map(d,function(a){return a?
h[a]._compile():null});e&&e.apply(null,a)})};d.prototype._load=function(a,e){function c(a){(a||{}).status<i.READY&&(a.status=i.READY);0===--k&&e()}var f=b.filter(a,function(a){return a&&(!h[a]||h[a].status<i.READY)}),g=f.length;if(0===g)e();else for(var k=g,j=0;j<g;j++)(function(a){function e(){f=h[a];if(f.status>=i.SAVED){var g=o(f);g.length?d.prototype._load(g,function(){c(f)}):c(f)}else b.log("It is not a valid CMD module: "+a),c()}var f=h[a]||(h[a]=new d(a,i.FETCHING));f.status>=i.FETCHED?e():
n(a,e)})(f[j])};d.prototype._compile=function(){function a(b){b=c(b,d.uri);b=h[b];if(!b)return null;if(b.status===i.COMPILING)return b.exports;b.parent=d;return b._compile()}var d=this;if(d.status===i.COMPILED)return d.exports;if(d.status<i.READY&&!g[d.realUri||d.uri])return null;d.status=i.COMPILING;a.async=function(a,b){d._use(a,b)};a.resolve=function(a){return c(a,d.uri)};a.cache=h;d.require=a;d.exports={};var f=d.factory;b.isFunction(f)?(m.push(d),e(f,d),m.pop()):void 0!==f&&(d.exports=f);d.status=
i.COMPILED;k(d);return d.exports};d._define=function(a,e,d){var f=arguments.length;1===f?(d=a,a=void 0):2===f&&(d=e,e=void 0,b.isArray(a)&&(e=a,a=void 0));!b.isArray(e)&&b.isFunction(d)&&(e=b.parseDependencies(d.toString()));var f={id:a,dependencies:e,factory:d},g;if(document.attachEvent){var k=b.getCurrentScript();k&&(g=b.unParseMap(b.getScriptAbsoluteSrc(k)));g||b.log("Failed to derive URI from interactive script for:",d.toString(),"warn")}if(k=a?c(a):g){if(k===g){var j=h[g];j&&(j.realUri&&j.status===
i.SAVED)&&(h[g]=null)}f=l(k,f);if(g){if((h[g]||{}).status===i.FETCHING)h[g]=f,f.realUri=g}else r||(r=f)}else u=f};d._getCompilingModule=function(){return m[m.length-1]};d._find=function(a){var e=[];b.forEach(b.keys(h),function(c){if(b.isString(a)&&-1<c.indexOf(a)||b.isRegExp(a)&&a.test(c))c=h[c],c.exports&&e.push(c.exports)});return e};d._modify=function(b,d){var f=c(b),k=h[f];k&&k.status===i.COMPILED?e(d,k):(g[f]||(g[f]=[]),g[f].push(d));return a};d.STATUS=i;d._resolve=b.id2Uri;d._fetch=b.fetch;
d.cache=h;var p={},q={},t={},u=null,r=null,v=[],w=new d(b.pageUri,i.COMPILED);a.use=function(b,e){var c=f.preload;c.length?w._use(c,function(){f.preload=[];w._use(b,e)}):w._use(b,e);return a};a.define=d._define;a.cache=d.cache;a.find=d._find;a.modify=d._modify;a.pluginSDK={Module:d,util:b,config:f}}(seajs,seajs._util,seajs._config),function(a,b,f){var d="seajs-ts="+b.now(),c=document.getElementById("seajsnode");c||(c=document.getElementsByTagName("script"),c=c[c.length-1]);var n=b.getScriptAbsoluteSrc(c)||
b.pageUri,n=b.dirname(function(a){if(a.indexOf("??")===-1)return a;var c=a.split("??"),a=c[0],c=b.filter(c[1].split(","),function(a){return a.indexOf("sea.js")!==-1});return a+c[0]}(n));b.loaderDir=n;var l=n.match(/^(.+\/)seajs\/[\d\.]+\/$/);l&&(n=l[1]);f.base=n;if(c=c.getAttribute("data-main"))f.main=c;f.charset="utf-8";a.config=function(e){for(var c in e)if(e.hasOwnProperty(c)){var o=f[c],j=e[c];if(o&&c==="alias")for(var h in j){if(j.hasOwnProperty(h)){var g=o[h],m=j[h];/^\d+\.\d+\.\d+$/.test(m)&&
(m=h+"/"+m+"/"+h);g&&g!==m&&b.log("The alias config is conflicted:","key =",'"'+h+'"',"previous =",'"'+g+'"',"current =",'"'+m+'"',"warn");o[h]=m}}else if(o&&(c==="map"||c==="preload")){b.isString(j)&&(j=[j]);b.forEach(j,function(a){a&&o.push(a)})}else f[c]=j}if((e=f.base)&&!b.isAbsolute(e))f.base=b.id2Uri((b.isRoot(e)?"":"./")+e+"/");if(f.debug===2){f.debug=1;a.config({map:[[/^.*$/,function(a){a.indexOf("seajs-ts=")===-1&&(a=a+((a.indexOf("?")===-1?"?":"&")+d));return a}]]})}if(f.debug)a.debug=!!f.debug;
return this};f.debug&&(a.debug=!!f.debug)}(seajs,seajs._util,seajs._config),function(a,b,f){a.log=b.log;a.importStyle=b.importStyle;a.config({alias:{seajs:b.loaderDir}});b.forEach(function(){var a=[],c=f.location.search,c=c.replace(/(seajs-\w+)(&|$)/g,"$1=1$2"),c=c+(" "+document.cookie);c.replace(/seajs-(\w+)=[1-9]/g,function(b,c){a.push(c)});return b.unique(a)}(),function(b){a.use("seajs/plugin-"+b);"debug"===b&&(a._use=a.use,a._useArgs=[],a.use=function(){a._useArgs.push(arguments);return a})})}(seajs,
seajs._util,this),function(a,b,f){var d=a._seajs;if(d&&!d.args)f.seajs=a._seajs;else{f.define=a.define;b.main&&a.use(b.main);if(b=(d||0).args)for(var d={"0":"config",1:"use",2:"define"},c=0;c<b.length;c+=2)a[d[b[c]]].apply(a,b[c+1]);f.define.cmd={};delete a.define;delete a._util;delete a._config;delete a._seajs}}(seajs,seajs._config,this),function(a,b){b.Qiyi=b.Qiyi||{};var f=b.Q;b.Q=b.Qiyi;var d,c;Qiyi.noConflict=function(){b.Q=f};Qiyi.ready=function(a){c=Q.liburl||"http://static.qiyi.com/js/lib/lib";
seajs.use(c,a||function(){})};Qiyi.PageInfo={};Qiyi.load=function(a){var b=Qiyi.projectName||"";d=Q.verurl||"http://static.qiyi.com/js/"+Qiyi.projectName+"/ver.js";if(!b)throw Error("\u672a\u6307\u5b9aprojectName");seajs.config({base:"http://static.qiyi.com/js/"+b});Qiyi.ready(function(){seajs.use(d,function(b){b.loadJob(a,function(a){a&&a.addJobs&&a.addJobs();a&&a.start&&a.start()})})})};window.addEventListener?window.addEventListener("load",function(){Qiyi.isWindowLoaded=!0},!1):window.attachEvent&&
window.attachEvent("onload",function(){Qiyi.isWindowLoaded=!0});var n=function(a){for(var a=a.split(";"),b=a.length,c={},d=0,f,g;d<b;d++)a[d]&&(g=a[d].split(":"),f=g[0],g=g[1],c[f]=g);return c},l=function(){function a(){if(!a.isReady){a.isReady=!0;for(var b=0,c=d.length;b<c;b++)d[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(c){setTimeout(b,1);return}a()}var c=!1,d=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,!1);a()}:document.attachEvent&&
(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!c)if(c=!0,"complete"===document.readyState)a.isReady=!0;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,!1),window.addEventListener("load",a,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var d=!1;try{d=null==window.frameElement}catch(j){}document.documentElement.doScroll&&d&&b()}})();return function(b){a.isReady?
b():d.push(b)}}();l.isReady=!1;l(function(){Q.ready(function(){var a=Qiyi.$("[data-widget]");a&&a.forEach(function(a){var a=Qiyi.$(a),b=a.attr("data-widget"),c=a.attr("data-async");try{var e=n(c)}catch(f){return!1}if("ready"==e.type)seajs.use(d,function(a){a.loadModule(b,function(){})});else if("load"==e.type)if(Qiyi.isWindowLoaded)seajs.use(d,function(a){a.loadModule(b,function(){})});else Qiyi.$(window).on("load",function(){seajs.use(d,function(a){a.loadModule(b,function(){})})});else if("trigger"==
e.type){var c=e.triggertype||"event",m=e.trigger;if("event"==c){var i=function(c){seajs.use(d,function(d){d.loadModule(b,function(b){a.un(m,i);b.trigger&&b.trigger(c)})})};a.on(m,i)}else if("lazyload"==c){var l=function(){seajs.use(d,function(a){a.loadModule(b,function(){Qiyi.$(window).un("scroll",q);Qiyi.$(window).un("resize",q)})})},q=function(){a.isInScreen()&&"inscreen"==m?l():!a.isInScreen()&&"outofscreen"==m&&l()};Qiyi.$(window).on("scroll",q);Qiyi.$(window).on("resize",q)}}})})})}(seajs,this));
